src/Data/Inputs.elm
src/Data/LifeCycle.elm
src/Data/Session.elm
src/Data/Simulator.elm
src/Page/Examples.elm
src/Page/Home.elm
src/Page/Simulator.elm
src/Views/Chart.elm
src/Views/Step.elm
src/Views/Summary.elm
tests/Data/SimulatorTest.elm

Use Inputs in Simulator.

---

src/Data/CountryProcess.elm
src/Data/Inputs.elm
src/Data/LifeCycle.elm
src/Data/Process.elm
src/Data/Simulator.elm
src/Data/Step.elm
src/Page/Simulator.elm
src/Views/Chart.elm
src/Views/Step.elm
styles.scss
tests/Data/SimulatorTest.elm

Allow adjusting the deying process weighting dynamically.

---

public/data/countries.json
public/data/materials.json
src/Data/Country.elm
src/Data/Db.elm
src/Data/Inputs.elm
src/Data/LifeCycle.elm
src/Data/Material.elm
src/Data/Process.elm
src/Data/Product.elm
src/Data/Simulator.elm
src/Data/Step.elm
src/Page/Simulator.elm
src/Request/Db.elm

This patch first loads Process database, then expand all other datasets populating fully qualified processes linked to them.

Load related processes in local data structures.

---

package-lock.json
package.json

Upgrade Parcel to v2.0.0 stable.

---

.github/workflows/node.js.yml
package-lock.json
package.json
src/Data/Inputs.elm
src/Data/Key.elm
src/Data/LifeCycle.elm
src/Data/Process.elm
src/Data/Simulator.elm
src/Data/Step.elm
src/Main.elm
src/Page/Simulator.elm
src/Views/Button.elm
src/Views/Comparator.elm
src/Views/Container.elm
src/Views/Format.elm
src/Views/Modal.elm
src/Views/Page.elm
src/Views/Step.elm
styles.scss
tests/Data/SimulatorTest.elm

[User Story](https://www.notion.so/8d0c859b065541388c910de2ac854913?v=21369a0f79db4cdcab3ca379ef893ba4&p=f4b4c9c518d548328a3c59cdf18a4f89)

Allow customizing step country electric mix impact.

---

elm.json
src/Views/Comparator.elm
src/Views/Comparator/Chart.elm

[User Story](https://www.notion.so/ETQ-Utilisateur-QJ-utilise-le-site-et-que-je-regarde-l-chelle-comparative-JV-que-les-mati-res-recyc-966fd0c227a14353a4163b4d79d10e58)

Improve comparative scale dataviz.

---

src/Data/Step.elm
src/Data/Transport.elm
tests/Data/LifeCycleTest.elm
tests/Data/SimulatorTest.elm

[User Story](https://www.notion.so/8d0c859b065541388c910de2ac854913?v=21369a0f79db4cdcab3ca379ef893ba4&p=fb25b064ff364645968c74bb081b9adc) /cc @paulboosz

Drop Material&Spinning step transport defaults.

---

public/data/materials.json

[User Story](https://www.notion.so/8d0c859b065541388c910de2ac854913?v=21369a0f79db4cdcab3ca379ef893ba4&p=77dfca76ee404af38df9956b3af2b96f)
Note: I didn't add a new test because I can't realistically add all possible combinations of input parameters.

Update recycled PET process UUID.

---

Procfile
README.md
package.json
server.js
src/Server.elm

Ongoing experimentation with @magopian.

Implement a minimalist HTTP API.

---

src/Data/Country.elm
src/Data/Formula.elm
src/Data/Inputs.elm
src/Data/Material.elm
src/Data/Sample.elm
src/Data/Step.elm
src/Data/Unit.elm
src/Page/Simulator.elm
src/Server.elm
src/Views/BarChart.elm
src/Views/Comparator.elm
src/Views/RangeSlider.elm
src/Views/Step.elm
tests/Data/FormulaTest.elm
tests/Data/UnitTest.elm

[User Story](https://www.notion.so/Impl-menter-le-type-Ratio-cc5891a355d9485bb13bce7f883930e7)

Implement ratio type

---

src/Page/Examples.elm

[User Story](https://www.notion.so/Ajouter-un-s-lecteur-d-impact-la-page-Exemples-427a3f6ca40c42fdb51eacae76dedaa6)

Add impact selector to Examples page.

---

src/Views/Impact.elm

[User Story](https://www.notion.so/Diff-rencier-le-score-PEF-des-autres-impacts-dans-le-menu-d-roulant-7b94a43ecfcb4329a938487e2833924a)

Distinguish PEF menu entry in impact selector.

---

public/data/impacts.json
src/Data/Impact.elm
src/Page/Examples.elm
src/Page/Explore/Impacts.elm
src/Page/Simulator.elm
src/Views/Impact.elm
styles.scss
tests/TestDb.elm-template

Added a short impact description in EN and FR. Mostly based on annexes 1 to 2 of PEF but I tried to synthetize, complete when necessary. Proof reading requested from Pascal

Add impact descriptions.

---

openapi.yaml
src/Data/Inputs.elm
src/Data/Product.elm
src/Data/Simulator.elm
src/Data/Step.elm
src/Data/Unit.elm
src/Main.elm
src/Page/Api.elm
src/Page/Changelog.elm
src/Page/Examples.elm
src/Page/Explore.elm
src/Page/Home.elm
src/Page/Simulator.elm
src/Page/Stats.elm
src/Route.elm
src/Server/Query.elm
src/Views/Comparator.elm
src/Views/Impact.elm
src/Views/Page.elm
src/Views/RangeSlider.elm
src/Views/Step.elm
src/Views/Summary.elm
styles.scss
tests/Data/ProductTest.elm
tests/Server/RouteTest.elm

[User Story](https://www.notion.so/PEFCR-A-F-2-5-Qualit-intrins-que-dans-Webapp-8b7b8e2197314566b1ed1c274f6079f8)

Implement product intrinsic quality.

---

.github/workflows/node.js.yml
package.json

This is an attempt at setting up an Elm dependencies cache strategy in CI & [CD](https://doc.scalingo.com/languages/nodejs/start#custom-cache-folder) contexts.

Cache Elm dependencies.

---

openapi.yaml
src/Data/Country.elm
src/Data/Product.elm
src/Server.elm
src/Server/Route.elm
tests/server.spec.js

[User Story](https://www.notion.so/Ajouter-les-points-d-entr-e-d-API-pour-les-produits-les-mati-res-et-les-pays-68fbcd2b7e394126825f91f2eeb9b6d5)

Add countries, materials & products API endpoints.

---

src/Data/Formula.elm
src/Data/Sample.elm
src/Data/Step.elm
src/Data/Transport.elm
tests/Data/FormulaTest.elm

[User Story](https://www.notion.so/R-gler-bug-de-non-ventilation-des-distances-de-transports-entre-les-pays-das-les-autres-tapes-que-C-f820aa1ba1eb46fd82746999d776b9ff)

Fix transport computations at the Ennoblement step.

---

openapi.yaml
public/data/materials.json
public/data/products.json
src/Data/Db.elm
src/Data/Inputs.elm
src/Data/Material.elm
src/Page/Explore.elm
src/Page/Explore/Materials.elm
src/Page/Simulator.elm
src/Server.elm
src/Server/Query.elm
tests/Server/RouteTest.elm
tests/server.spec.js

[User Story](https://www.notion.so/Renommer-les-identifiants-produits-et-mati-res-0a1a28f2fc1645cebaa791d26a7b2a39)

Update legibility of materials & product identifiers.

---

package-lock.json
package.json
server.js

This fixes previous attempt (#84)

Upgrade npm dependencies to their latest versions.

---

public/data/processes.json

[User Story](https://www.notion.so/ETQ-1083-Promod-JV-pouvoir-int-grer-le-d-lavage-d-un-Jean-Etudier-l-tape-de-d-lavage-d17537cc497747ddafd076f05766f41b)
There are a number (12) of fading processes in Base Impacts. For this first implementation I just added one process (the upper bound process).

Add fading process for jeans

---

src/Page/Home.elm
src/Page/Simulator.elm
src/Page/Simulator/ViewMode.elm
src/Route.elm
src/Views/Page.elm
src/Views/Step.elm
src/Views/Summary.elm
styles.scss

[User Story](https://www.notion.so/Permettre-d-ouvrir-la-vue-d-taill-e-sur-une-tape-directement-depuis-l-tape-acdba6e58b68485ca6c03cc4f3305ecc)

Add links to detailed/simple step views.

---

public/data/impacts.json
src/Data/Impact.elm
src/Page/Explore/Impacts.elm
src/Views/Impact.elm

Cf https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=da516c13667d4d098ba5d5581ca9ebae

Add a "source" url to the impacts

---

src/Data/Session.elm
src/Main.elm
src/Page/Simulator.elm

cf https://www.notion.so/Pr-server-la-simulation-en-cours-lors-de-la-navigation-au-sein-du-site-8eb4fc52098a43a8b3cbf5d73e9b1d37

Save the current simulation

---

elm.json
review/src/ReviewConfig.elm
src/Data/Simulator.elm
src/Data/Step.elm
src/Page/Simulator.elm
src/Page/Simulator/ViewMode.elm
src/Views/Comparator.elm
src/Views/Dataviz.elm
src/Views/Debug.elm
src/Views/Step.elm

[User Story](https://www.notion.so/UI-Analyse-de-besoins-de-la-nouvelle-page-de-r-sultats-95a98615d67948579f92a17b6c581abb)

Add a data visualization tab.

---

README.md
index.html
index.js
lib/index.js
openapi.yaml
package-lock.json
package.json
public/data/processes.json
public/pages/accessibilité.md
public/pages/mentions-légales.md
src/Data/Env.elm
src/Data/Gitbook.elm
src/Data/Impact.elm
src/Data/Step.elm
src/Page/Api.elm
src/Page/Changelog.elm
src/Request/Gitbook.elm
src/Request/Github.elm
src/Server.elm
src/Views/Alert.elm
src/Views/Markdown.elm
src/Views/Page.elm
src/Views/Summary.elm
tests/Data/GitbookTest.elm
tests/server.spec.js

[User Story](https://www.notion.so/Bascule-Ecobalyse-3097aa577abf45b2a46696ae87617cde)

Update product name from Wikicarbone to Ecobalyse.

---

src/Data/Env.elm
src/Server/Query.elm
src/Views/Step.elm
tests/server.spec.js

After discussion, we settled on making 40% the new max waste ratio at the Making stage.

Update making waste maximum ratio.

---

src/Data/Food/Db.elm
src/Data/Food/Product.elm
src/Page/Food/Simulator.elm
src/Request/Food/Db.elm

This PR is larger than I initially thought: I took the opportunity to better
represent and link the processes and products. Hopefully it makes more sense
like that.
A high level view of the structure and hierarchy can be found [here](https://github.com/MTES-MCT/ecobalyse/pull/148/files#diff-a5f53fb3f1c6f09e8d7dbb4fced7ea679a4db6d4328ac61b32df32bb09b90fcfR12-R20).

Use the new detailed export from Agribalyse

---

src/Data/Food/Product.elm
src/Page/Food/Simulator.elm

WIP: the impacts percentages aren't properly computed

[food] decode duplicated processes in products.json

---

src/Page/Food/Simulator.elm
styles.scss

Pair-programmed with @magopian

Render Food item comments.

---

src/Page/Food/Simulator.elm

Paired & reviewed with @magopian

Expose explicit boolean arguments.

---

src/Page/Food/Simulator.elm
src/Views/Component/Summary.elm
src/Views/Textile/Summary.elm
styles.scss

Partially paired with @magopian

Improve Food UI layout & responsiveness.

---

src/Page/Food/Builder.elm
src/Views/Page.elm

[User Story](https://www.notion.so/Bandeau-Alpha-sur-le-configurateur-Food-9214c9b15a904bf1ad1c16fd28cb9cee)

Add a warning about ongoing development in Food pages.

---

public/data/food/ingredients.json
public/data/food/processes/builder.json

Related to https://github.com/MTES-MCT/ecobalyse-data/pull/11

Add a new "flour" (complex) ingredient

---

public/data/food/ingredients.json
public/data/food/processes/builder.json

Related to https://github.com/MTES-MCT/ecobalyse-data/pull/14

Add new agricultural ingredients

---

src/Data/Impact.elm
src/Page/Food/Builder.elm
src/Page/Food/Explore.elm
src/Page/Home.elm
src/Page/Textile/Examples.elm
src/Page/Textile/Simulator.elm
src/Route.elm
src/Server/Route.elm
src/Views/Page.elm
src/Views/Textile/Summary.elm

[User Story](https://www.notion.so/Afficher-le-score-d-impacts-par-d-faut-la-place-du-score-PEF-d6e11a0f173343fea811a5959f4e3070)

Set default impact for Food pages to ecs.

---

src/Page/Food/Builder.elm
src/Views/Format.elm

cf [notion](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=90c1a9d44ff845c090b6f491065ba2ef&p=13b41d53b0354d1ea5cab648107f7ad2&pm=s)

Display the impact per kg of product

---

lib/charts/food-comparator.js
lib/charts/index.js
src/Data/Bookmark.elm
src/Data/Impact.elm
src/Data/Scope.elm
src/Data/Session.elm
src/Page/Food/Builder.elm
src/Page/Textile/Simulator.elm
src/Views/Bookmark.elm
src/Views/Comparator.elm
src/Views/Dataviz.elm
src/Views/Textile/Comparator.elm
tests/Data/Textile/LifeCycleTest.elm
tests/Data/TransportTest.elm

[User Story](https://www.notion.so/Cr-ation-d-une-premi-re-fonction-de-comparaison-de-r-sultats-2c7d6aa335ec4ecd9e104bc8f1549089)

Allow comparing food recipes.

---

lib/charts/food-comparator.js
src/Data/Food/Builder/Recipe.elm
src/Data/Impact.elm
src/Page/Food/Builder.elm
src/Page/Textile/Simulator.elm
src/Views/Comparator.elm
src/Views/Format.elm
tests/Data/Food/Builder/RecipeTest.elm
tests/Data/ImpactTest.elm

[User Story](https://www.notion.so/Comparateur-d-impact-comparer-l-impact-par-kg-6b6e7ab3144841818b967b8126d68601)

Allow comparing food products per item or kg of product.

---

public/data/food/ingredients.json

[User Story](https://www.notion.so/Introduire-le-rapport-cru-cuit-321b61f10081406fb35b633c4b572975)
[documentation](https://fabrique-numerique.gitbook.io/ecobalyse/alimentaire/rapport-cru-cuit)

Implement raw_to_cooked_ratio

---

src/Data/Impact.elm
src/Page/Food/Builder.elm
src/Views/Format.elm
tests/Data/ImpactTest.elm

cf [notion](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=90c1a9d44ff845c090b6f491065ba2ef&p=c0d9599591084dbeba62132aa8c49202&pm=s)

Display a score out of 100

---

src/Data/Country.elm
src/Data/Food/Builder/Query.elm
src/Data/Food/Builder/Recipe.elm
src/Data/Food/Ingredient.elm
src/Data/Gitbook.elm
src/Data/Impact.elm
src/Data/Textile/Inputs.elm
src/Data/Textile/Material.elm
src/Data/Textile/Printing.elm
src/Data/Textile/Product.elm
src/Data/Unit.elm
src/Page/Food/Builder.elm
tests/Data/Food/Builder/RecipeTest.elm
tests/Data/UnitTest.elm

[User Story](https://www.notion.so/Introduire-le-rapport-cru-cuit-321b61f10081406fb35b633c4b572975)
[Methodology](https://fabrique-numerique.gitbook.io/ecobalyse/alimentaire/rapport-cru-cuit)
Note: depends on fix in #206

Apply raw to cooked ratio to ingredients mass.

---

src/Data/Dataset.elm
src/Data/Scope.elm
src/Data/Textile/Db.elm
src/Main.elm
src/Page/Explore.elm
src/Page/Explore/Common.elm
src/Page/Explore/Countries.elm
src/Page/Explore/FoodIngredients.elm
src/Page/Explore/Impacts.elm
src/Page/Explore/Table.elm
src/Page/Explore/TextileMaterials.elm
src/Page/Explore/TextileProducts.elm
src/Page/Food/Builder.elm
src/Route.elm
src/Views/Page.elm

[User Story](https://www.notion.so/Initier-un-explorateur-d-ingr-dients-4a39cf204de145c9a0f81d03c096e493)

Implement a Food ingredients explorer.

---

src/Data/Impact.elm
src/Page/Food/Builder.elm
src/Views/Format.elm
tests/Data/ImpactTest.elm

[User story](https://www.notion.so/RESULTATS-Introduire-des-chelles-intra-cat-gorie-pour-la-note-A-B-C-D-E-c3b7e176d44d4be985612ccf2dce3266)

Implement food category scales based scoring.

---

src/Page/Food/Builder.elm

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=90c1a9d44ff845c090b6f491065ba2ef&p=20b0c29a1a164beb827b86f07953ce2a&pm=s)

Revert to the default country of origin when switching ingredients

---

src/Data/Food/Category.elm
src/Data/Impact.elm
tests/Data/Food/Builder/RecipeTest.elm
tests/Data/ImpactTest.elm
tests/e2e-food.json

[User Story](https://www.notion.so/RESULTATS-Corriger-les-bornes-des-sous-scores-suite-investigation-sur-les-incoh-rences-e3ce58b448c148858710d09d38490516)

Adjust food category bounds.

---

public/data/impacts.json
src/Data/Impact.elm
src/Page/Food/Builder.elm
src/Views/Comparator.elm
tests/Data/Food/Builder/RecipeTest.elm
tests/e2e-food.json

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=90c1a9d44ff845c090b6f491065ba2ef&p=18b996c9758f45779b13777eb6d9ac38&pm=s)

Modify the comparator modal

---

openapi.yaml
src/Data/Food/Builder/Query.elm
src/Data/Food/Builder/Recipe.elm
src/Data/Food/Ingredient.elm
src/Page/Api.elm
src/Server.elm
src/Server/Query.elm
tests/Data/Food/Builder/RecipeTest.elm
tests/Server/RouteTest.elm
tests/e2e-food.json
tests/server.spec.js

[User Story](https://www.notion.so/Ajouter-les-param-tres-de-bonus-l-API-alimentaire-84fb88128c98449cbfdb97a3a77de569)

Expose bonuses as API parameters.

---

src/Data/Food/Builder/Recipe.elm
src/Data/Impact.elm
src/Page/Api.elm
src/Page/Food/Builder.elm
tests/Data/Food/Builder/RecipeTest.elm

[user story](https://www.notion.so/Afficher-l-ecoscore-bonus-inclus-dans-l-API-8a228998555b49cfb130219d09910dbd)

Take bonuses into account for ecs computation in the API

---

src/Data/Textile/Inputs.elm
src/Page/Food/Builder.elm
src/Page/Textile/Examples.elm
src/Page/Textile/Simulator.elm
src/Views/Comparator.elm
src/Views/Textile/ComparativeChart.elm
src/Views/Textile/Summary.elm

[user story](https://www.notion.so/Info-bulles-graphe-R-sultat-000634b5c7de4d3c902d1f1557b124b0)

Tooltips on comparative charts

---

src/Views/Textile/ComparativeChart.elm

[user story](https://www.notion.so/Investigations-sur-les-graphes-de-R-sultat-0da08d900f3047a7b688d7e4f125feaa)

Chart comparison with different countries but same parameters

---

src/Data/Food/Builder/Query.elm
src/Data/Food/Ingredient.elm
src/Data/Textile/Inputs.elm
src/Page/Textile/Simulator.elm
src/Server.elm
src/Views/Bookmark.elm

[User Story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=37bf8aeb782747c3bf744ecaeafefd04)

Allow exporting API requests from Web, expose Web url from API results.

---

data/docker/Dockerfile
data/docker/requirements.txt
data/notebooks/explore.py

Impacts were at zero after copying an activity
Updated Brightway so that the issue seems fixed
Also updated Python to 3.11

Zero impact if copied activity

---

src/Page/Food/Builder.elm
styles.scss

[User Story](https://www.notion.so/Ajuster-la-pr-sentation-de-la-contribution-des-bonus-aux-impacts-ingr-dients-17cb8ae9487445c3b90ded98e6aac561)

Improve rendering of ingredient bonuses & transports.

---

lib/charts/food-comparator.js
review/src/ReviewConfig.elm
src/Data/Color.elm
src/Data/Food/Recipe.elm
src/Data/Impact.elm
src/Page/Explore.elm
src/Page/Food.elm
src/Page/Home.elm
src/Page/Textile/Simulator.elm
src/Views/Bookmark.elm
src/Views/Comparator.elm
src/Views/ImpactTabs.elm
src/Views/Modal.elm

[user story](https://www.notion.so/Ajouter-un-onglet-tapes-dans-la-comparaison-alimentaire-f16987b8c6c247bfacfc1baa810506af)

Allow comparing steps impacts for food products.

---

openapi.yaml
src/Data/Textile/Knitting.elm
src/Data/Textile/Process.elm
src/Page/Api.elm
src/Views/Bookmark.elm
src/Views/Textile/Step.elm
tests/Data/Textile/ProductTest.elm

[user story](https://www.notion.so/Tricotage-modif-nomenclature-00c4927b01584c03bfc770a4a493006f)

Rename some knitting processes

---

src/Data/Gitbook.elm

[user story](https://www.notion.so/Lien-corriger-_-Filature-5e93958341e14f52a713b5d3dc3c5bfd)

Fix spinning docs link

---

data/common/export.py
data/food/activities.json
data/food/activities_to_create.json
public/data/food/ingredients.json
public/data/food/processes.json

[User Story](https://www.notion.so/Cr-er-variantes-de-poulet-porc-1d7d140acc5d4891ad3efc08583182a5?pvs=4)

chicken-organic-fr

---

public/data/impacts.json

[User story](https://www.notion.so/Renommer-score-d-impact-en-co-t-environnemental-cba541a893df4ef8aebbd0fe01418e41)

Rename "Score d'impacts" to "Coût environnemental".

---

src/Page/Food.elm
src/Page/Textile/Simulator.elm
src/Views/ImpactTabs.elm

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=c16a220ef5e84b92a4a3865092cdcc31&pm=s)

Reorder the impacts tab

---

src/Data/Gitbook.elm
src/Page/Food.elm
src/Views/Textile/Step.elm

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=18967ae4ff6c466fb4ade87583ab7997&pm=s)

Links to docs and explorer

---

src/Views/Textile/Step.elm

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=cfb801a91618459d95f95dce1188c055&pm=s)

Harmonize impact display and fonts

---

src/Views/Textile/Step.elm

Add missing left border color on textile detailed views

---

lib/charts/base.js
lib/charts/food-comparator.js

[User Story](https://www.notion.so/Permettre-d-exporter-les-graphes-Highcharts-en-JPG-ou-PNG-7e2ea6c5d35b4bbe8edff97f32a78b1a)
Allow users to save charts as images:
Generated image sample:

Allow saving charts as images.

---

data/food/activities.json
data/notebooks/ingredients.py

Removed subingredients since we don't have complex ingredients
Complex ingredients created during food export have been replaced by constructed processes created during AGB import

Removed subingredients as we don't have complex ingredients now

---

src/Data/Textile/Inputs.elm
src/Page/Api.elm
src/Page/Food.elm
src/Page/Textile/Simulator.elm
src/Server/Query.elm
src/Views/BaseElement.elm
src/Views/Textile/Step.elm
styles.scss
tests/Server/RouteTest.elm
tests/server.spec.js

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=f872a7b99cbd4a19b9963b857846e188&pm=s)

Harmonize textile step disabling

---

src/Data/Textile/Simulator.elm
src/Page/Textile/Simulator.elm

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=46048edc1b244c279953533552989163&pm=s)

Fix mass computation before spinning

---

src/Data/Impact.elm
src/Views/ImpactTabs.elm
src/Views/Textile/Step.elm

[user story](https://www.notion.so/Renommer-Fin-de-vie-hors-Europe-en-Export-hors-Europe-c8e513a505c84276a7d57aef3f926212)

Rename "out of Europe" end of life complement

---

data/notebooks/ingredients.py

Added a filter above the activity list in the ingredient editor

Activity filter

---

data/notebooks/ingredients.py

In the ingredient editor the ingredient filter was applied during read. So the pushed ingredients were the filtered list. The filter has been moved from the read function to the list function

Moved the filter from the read function to the list function

---

data/common/export.py
data/common/import_.py
data/import_agribalyse.py
data/import_ecoinvent.py

These are provided by ecoinvent and seem to be present in ei 3.9.2.
they are used in EF3.1 adapted

Add two additional substances

---

data/notebooks/ingredients.py

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=f8191c80a71f486b9c041f037619978c&pm=s)

Display the surface in ingredient editor

---

src/Page/Food.elm
src/Page/Textile/Simulator.elm

[user story](https://www.notion.so/Harmonisation-r-initialisation-de-la-simulation-9f64a9ade51c4690a4d0ed26e52ad5ba)

Harmonize simulator reset

---

src/Data/AutocompleteSelector.elm
src/Data/Food/Query.elm
src/Data/Food/Retail.elm
src/Page/Food.elm
src/Page/Textile/Simulator.elm
src/Views/BaseElement.elm
src/Views/Textile/Step.elm
styles.scss

[user story](https://www.notion.so/Int-gration-d-exemples-de-produits-alimentaires-e2a5df9775874d10a1dbee8a8c5f9471)

Food examples autocomplete

---

src/Data/Food/Query.elm

Fix the frozen products so they have the proper freezing process instead of refrigeration (asked by Pascal and Lisa)

Replace refrigeration with freezing for frozen food products

---

src/Data/Gitbook.elm
src/Data/Textile/Step/Label.elm
tests/Data/GitbookTest.elm

[user story](https://www.notion.so/Le-lien-vers-la-doc-de-l-tape-mati-res-pointe-vers-celle-de-la-filature-ac53b102540f429cbe7b866489a41658)

Fix the textile material step link to the docs

---

openapi.yaml
public/data/textile/products.json
src/Data/Textile/Inputs.elm
src/Data/Textile/Product.elm
src/Data/Textile/Simulator.elm
src/Data/Textile/Step.elm
src/Page/Api.elm
src/Page/Explore/TextileProducts.elm
src/Page/Textile/Simulator.elm
src/Views/Textile/Step.elm
tests/Data/Textile/InputsTest.elm
tests/Data/Textile/SimulatorTest.elm
tests/Server/RouteTest.elm

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=5cec5bca85794d37b39602650601eb04&pm=s)

Sélection d'exemples de produits textile

---

openapi.yaml
src/Data/Textile/Inputs.elm
src/Page/Api.elm
src/Page/Textile/Simulator.elm
src/Server/Query.elm
src/Views/Textile/Step.elm
tests/Server/RouteTest.elm
tests/e2e-textile.json
tests/server.spec.js

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=4ad9372a0dc9461a836d6e080c110f13&pm=s)

Rename disabledFading to fading

---

src/Views/Textile/Step.elm

oops... probably slipped through while working on #433

Fix the fading checkbox

---

src/Views/Textile/Step.elm

[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=fb3b165522f24dea80ceb8d5734c0af2&pm=s)

Also display the fabric process field in the simple view

---

data/notebooks/ingredients.py

merge the code from the ingredients branch

reload the list when changing contributor (renamed institut→contributor)

---

data/food/export.py
data/notebooks/ingredients.py

Search in different databases (such as ecopasto or ginko) in the ingredient editor.
Allow to export the impacts from these databases

multiple databases for ingredient editor

---

data/import_agribalyse.py

[story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=37bf8aeb782747c3bf744ecaeafefd04&p=931ec622d71649e09706a33a23af512e&pm=s)

integration of CTCPA processes

---

src/Data/Textile/Inputs.elm

[User story](https://www.notion.so/Bug-Phase-Usage-Pantalon-52ed7276757e4c9198a7ffb001aef167)

Fix erroneous product category for trousers.

---

src/Page/Textile/Simulator.elm

[user story](https://www.notion.so/Repositionner-le-type-de-produit-dans-la-phase-d-usage-e7ad8846ff13420a92301ec081b198ce)

Add a textile product type selector

---

data/notebooks/explore.py

- Display 16 subimpacts instead of all EF3.1adapted subimpacts
- Refactored EF31 specific code with data from impacts.json

Explorer16impacts

---

data/notebooks/textile_processes.py

notebook to download textile processes as CSV and display an horizontal stacked bar chart with the impacts

textile processes notebook

---

data/food/activities_to_create.json

fix ids for subprocesses of "organic beef (created by Ecobalyse)"

add ids to search to avoid wrong process selection

---

src/Data/Food/EcosystemicServices.elm
tests/Data/Food/RecipeTest.elm

[User Story](https://www.notion.so/Int-gration-Ecoinvent-Mix-Chaleur-f250a03d16754bd2b191bc3738f1b4cc)

Update livestock density coefficient to 3000.

---

data/notebooks/ingredients.py

- Added fields for parameters used to compuse SE
- Feed the surface from the simapro api to the land_footprint field

Added 3 fields to the ingredient editor

---

bin/build-example-ids
public/data/food/examples.json
public/data/textile/examples.json
src/Data/Dataset.elm
src/Data/Food/ExampleProduct.elm
src/Data/Textile/ExampleProduct.elm
src/Page/Explore.elm
src/Page/Explore/Common.elm
src/Page/Explore/Countries.elm
src/Page/Explore/FoodExamples.elm
src/Page/Explore/FoodIngredients.elm
src/Page/Explore/FoodProcesses.elm
src/Page/Explore/Impacts.elm
src/Page/Explore/Table.elm
src/Page/Explore/TextileExamples.elm
src/Page/Explore/TextileMaterials.elm
src/Page/Explore/TextileProcesses.elm
src/Page/Explore/TextileProducts.elm
styles.scss

[User Story](https://www.notion.so/Mettre-en-place-un-outil-process-de-suivi-des-volutions-7bdf9a73024d4c889138a74dd1bab96d)

Add product examples to the explore section.

---

data/food/activities.json
public/data/food/ingredients.json
tests/Data/Food/RecipeTest.elm

Vegetal complements were lacking for a few ingredients. This PR fills the gap

Compléments végétaux pour flour-organic

---

src/Data/Session.elm
src/Page/Food.elm
src/Page/Textile/Simulator.elm
src/Views/Comparator.elm

Add buttons to select and deselect all compared simulations.

---

public/data/impacts.json
src/Data/Gitbook.elm
src/Data/Impact/Definition.elm
src/Page/Explore/Impacts.elm
src/Views/Impact.elm

[User Story](https://www.notion.so/Supprimer-dans-l-explorateur-textile-les-colonnes-et-donn-es-niveau-de-qualit-et-source-3f443b35990b4c1c9a4034dce470b836)

Remove obsolete "source" & "quality" impacts definition data.

---

src/Data/Textile/ExampleProduct.elm
src/Page/Textile/Simulator.elm

As discussed this afternoon ([user story](https://www.notion.so/Reprendre-le-libell-des-exemples-pour-mise-en-bookmark-1374ad360b4844718fe7ce356345002f))

Suggest bookmark name from existing example

---

public/data/textile/products.json
src/Data/Textile/Product.elm

[User Story](https://www.notion.so/Nouvelles-cat-gories-de-produits-textile-eb11e26b6ec742f69e9e496b65bc109e)

Add new textile product categories.

---

src/Data/Textile/Simulator.elm
src/Views/Comparator.elm

See relavant Mattermost conversation.

Apply durability to individual step impact in chart.

---

public/data/textile/examples.json

See this [Mattermost thread](https://mattermost.incubateur.net/fabnum-mte/pl/kyxtx3xu1fbifrw7nrd75w7kha) for context.

Add new product examples.

---

public/data/textile/products.json
tests/Data/Textile/SimulatorTest.elm

[user story](https://www.notion.so/Valeurs-par-d-faut-pour-les-param-tres-de-durabilit-cc71dce8691548139feaedb827af3957)

Update product categories economics default values.

---

src/Views/Textile/Step.elm

To reviewers: well done for the project. Looks amazing!
👋🏼 to @n1k0 @magopian!

Fix typo on country tooltip

---

src/Data/Textile/Step.elm
src/Page/Api.elm

[user story](https://www.notion.so/93ef4c3a503a48dbb6d3343a1fba142b)

Apply complements to textile API steps scores.

---

src/Data/Impact.elm
src/Page/Api.elm

[user story](https://www.notion.so/08b51954f9e44397ab2276fc4bcb7a32)

Harmonize ecosystemic services values in the API.

---

.env.sample
README.md
backend/backend/settings.py
index.js
src/Data/Session.elm
src/Main.elm
src/Page/Explore.elm
src/Page/Home.elm
src/Route.elm
src/Views/Page.elm
styles.scss

Prepare staging.

---

src/Data/Textile/Simulator.elm

[Context](https://chat.ecobalyse.fr/ecobalyse/pl/dg4zu5dcepykdphtf37y378uso)

Fix custom textile fabric process waste wasn't used.

---

.husky/pre-commit
public/data/textile/products.json
src/Data/Textile/Product.elm
src/Data/Textile/Query.elm
src/Page/Explore/Countries.elm
src/Page/Explore/FoodExamples.elm
src/Page/Explore/FoodIngredients.elm
src/Page/Explore/FoodProcesses.elm
src/Page/Explore/Impacts.elm
src/Page/Explore/Table.elm
src/Page/Explore/TextileExamples.elm
src/Page/Explore/TextileMaterials.elm
src/Page/Explore/TextileProcesses.elm
src/Page/Explore/TextileProducts.elm
src/Page/Textile.elm
src/Views/Textile/Step.elm
tests/Data/Textile/QueryTest.elm

[User story](https://www.notion.so/Requestionner-les-param-tres-attach-s-au-champ-cat-gorie-ac862d35339b4f70abde3901d7dd32f4#8ececf00a8d9413d8c5aef569fe79383)

Improve textile product category related behaviors.

---

.github/workflows/semantic-pr.yml

In order to facilitate release creation, we need a consistent naming in PR titles.
Use [semantic-pr](https://github.com/amannn/action-semantic-pull-request) to force PR titles to respect the [conventional commit recommandations](https://www.conventionalcommits.org)
For example, here are some valid PR titles:
Example of valid pull request titles:
- fix: Correct typo
- feat: Add support for Node.js 18
- refactor!: Drop support for Node.js 12
- feat(ui): Add `Button` component

chore: add semantic-pr

---

public/data/textile/examples.json
src/Data/Textile/Inputs.elm
src/Data/Textile/Product.elm
src/Data/Textile/Simulator.elm
src/Page/Explore/TextileProducts.elm
src/Views/Textile/Step.elm
tests/e2e-textile.json

[User story](https://www.notion.so/Bug-activation-d-sactivation-du-d-lavage-63d94a65203a4bc7be7ff8ab43e4c111)

fix: fix fading UI activation status bug.

---

src/Data/Split.elm
src/Data/Textile/Fabric.elm
src/Data/Textile/Simulator.elm
src/Page/Textile.elm
src/Views/Textile/Step.elm
tests/Data/Textile/FabricTest.elm

[User story](https://www.notion.so/Bug-API-prise-en-compte-du-proc-d-de-tricotage-52a9084b9f404f1faf14b9d27a2339cf), [Mattermost thread](https://mattermost.incubateur.net/fabnum-mte/pl/6e39gz8tsfyjir1wf4uopxf1ny)

fix(api,ui): Use custom waste/complexity and product defaults.

---

.github/workflows/node.js.yml
bin/build-db
package.json

This is a commit I didn't push to recently landed #646.

fix: avoid building detailed impacts in production.

---

src/Page/Food.elm
src/Page/Textile.elm
src/Views/AutocompleteSelector.elm

[User story](https://www.notion.so/Proposer-un-process-permettant-de-collecter-des-propositions-de-nouvelles-cat-gories-7007322578b34fcabf859fb126bee90b)

feat: add a link to the new product category gform.

---

data/food/activities.json
public/data/food/ingredients.json
public/data/food/processes.json
public/data/food/processes_impacts.json
tests/server.spec.js

[User Story](https://www.notion.so/Clarifier-la-structure-des-ingr-dients-7e81c6d0c060462a928a90ac46e85d4b?pvs=4)
not sure about the semantic name of the PR. I put `feat` as it changes names for the end user

feat: clarify ingredients names (bio, conv) and origin (France, EU, Hors-EU)

---

src/Data/Dataset.elm
src/Data/Food/Db.elm
src/Data/Food/Ingredient.elm
src/Data/Food/Process.elm
src/Data/Food/Recipe.elm
src/Page/Explore/FoodIngredients.elm
src/Page/Explore/FoodProcesses.elm
src/Page/Food.elm
src/Server.elm
src/Server/Query.elm
src/Views/BaseElement.elm
src/Views/Textile/Step.elm
tests/Data/Food/Fixtures.elm
tests/Data/Food/ProcessTest.elm
tests/Data/Food/RecipeTest.elm

[User story](https://www.notion.so/Augmenter-la-visibilit-du-choix-ingr-dient-ICV-source-360b90ee35d24afdaca58cbe9194eb90)

feat(food,ui): render agribalyse process name in ingredient selector.

---

src/Data/Common/Db.elm
src/Data/Impact.elm
src/Page/Food.elm
src/Page/Textile.elm
src/Static/Db.elm
src/Views/Sidebar.elm

[User story](https://www.notion.so/Supprimer-le-code-li-la-pond-ration-de-l-ecotox-89f016a508aa4688bf20cb32ac001226)

chore: remove obsolete adjustable ecotox weighting feat.

---

.github/workflows/node.js.yml
openapi.yaml
package-lock.json
package.json

We've been serving an invalid openapi spec for long it seems. This patch fixes it and adds OpenAPI validation to CI.

fix(api): Fix invalid openapi format

---

package.json
src/Data/Split.elm
src/Data/Textile/Query.elm
src/Server/Query.elm
tests/Data/SplitTest.elm
tests/Data/Textile/QueryTest.elm

[user story](https://www.notion.so/BUG-API-Contr-le-de-la-somme-des-mati-res-1af0370afefa43ae97438295b771b5b1)

fix(api): Fix material shares sum rounding precision error.

---

.github/workflows/release-please.yml

The data-dir in needed before building the app or release please will fail.
We need to clone the data dir before trying to build the app.

fix: data-dir is needed before build

---

src/Page/Textile.elm

[User story](https://www.notion.so/Renommer-l-onglet-Mode-avanc-en-Mode-exploratoire-et-non-p-dagogique-d98a9845ff29489a991a509ebcc50dc6)

chore(ui): Rename learning tab to exploratory tab.

---

README.md

Added more detail on deployment mecanism between ecobalyse and ecobalyse_private

docs: update readme ecobalyse private

---

data/notebooks/ingredients.py

This PR allows to download the list of activities (ingredients/processes) from the ingredients editor, and upload a modified list.

feat: download and upload buttons above the list of activities

---

public/data/textile/examples.json

[User story](https://www.notion.so/Ajustement-du-param-trage-des-pulls-5acd099e187a41b1bfd710219323eab6?pvs=4)

fix: update pull examples data

---

backend/textile/choices.py
openapi.yaml
src/Data/Textile/Economics.elm

[User story](https://www.notion.so/Suppression-de-la-r-f-rence-aux-services-de-garantie-durabilit-c60b6651d0a84368b8dc8aded15b7b5c)

chore: rename business services

---

src/Page/Explore.elm
src/Page/Food.elm
src/Page/Textile.elm
src/Views/BaseElement.elm
src/Views/Component/MassInput.elm
src/Views/Component/SplitInput.elm
src/Views/Textile/Step.elm

[user story](https://www.notion.so/Ajouter-un-moyen-d-acc-der-la-fiche-explorateur-d-un-ingr-dient-le-calculateur-f67f1dfba529443a9a08dc6279d93ecb)
https://github.com/user-attachments/assets/cf5989af-f799-46cf-a63d-63d5149e4cc4

feat: add button to open a material/ingredient details modal.

---

src/Data/Github.elm
src/Data/Session.elm
src/Main.elm
src/Request/Github.elm
src/Request/Version.elm
src/Views/Page.elm
styles.scss

[User story](https://www.notion.so/Comment-mat-rialiser-le-s-lecteur-de-version-dans-l-UI-d27ff90c71ab4f959163fe0441e72d68)

feat: add a version selector widget.

---

src/Data/Textile/Query.elm

[Bug report on Notion](https://www.notion.so/BUG-Confection-lev-e-pour-un-article-remanufactur-d3bedac9739d47318bc30a7adb8c358e)

fix: accept custom making complexity for upcycled garments.

---

package.json

Because we're all tired with this I guess:

fix: make scalingo not segfaulting.

---

data/Makefile
data/README.md
data/docker/Dockerfile
data/docker/entrypoint.sh

Shorter, better Makefile and better output

chore: Better makefile

---

package-lock.json

The previous version didn't install properly on mac.

chore: cleanup package-lock.json.

---

public/data/textile/examples.json

minor typo fixed in the textile examples

chore(data): fixed typo paysane→paysanne

---

bin/build-db
data/textile/activities.json
data/textile/export.py
package-lock.json
package.json
public/data/countries.json
public/data/textile/materials.json
public/data/textile/processes.json
public/data/textile/products.json
src/Data/Country.elm
src/Data/Dataset.elm
src/Data/Textile/Material.elm
src/Data/Textile/Process.elm
src/Data/Textile/Product.elm
src/Page/Explore.elm
src/Page/Explore/TextileProcesses.elm
tests/Data/Textile/FormulaTest.elm

Textile processes JSON file has a `uuid` field which does not contain actual UUIDs. This patch is part of a [broader work on file format homogeneization](https://www.notion.so/Refonte-fichiers-proc-d-s-2ac499dada8f4565baa6adf28c43cbde). TL;DR: `"uuid": "elec-medium-region-asia"` is a concern.
- Rename `uuid` to `id` for consistency with other processes files
- Create an actual UUID when an invalid one exists, keep valid ones
- Update all relations to these identifiers
- Move the old invalid uuid value into the comment field for archiving
- Changing primary keys should never be done, but here, we really really really have to. **THIS DOES NOT BREAK API COMPATIBILITY THOUGH**
- An invalid link to non-existent recycled viscose existed in `materials.json`  has been removed in …

fix(data)!: Update textile process ids to use UUID format

---

package-lock.json
package.json

The UI is broken since we upgraded Highcharts.js to v12 (white page of death).
Revert Highcharts to v11. We may upgrade to v12 later, but no need to rush.
UI shouldn't be broken anymore (no white page of death).

fix: broken homepage after upgrading highcharts

---

.pre-commit-config.yaml

This isn't useful anymore. I even wonder if it has ever worked 🤔

chore: remove obsolete pre-commit command.

---

openapi.yaml
src/Server/Query.elm
tests/Server/RouteTest.elm
tests/e2e-textile.json

Unaddressed review comment by @vjousse in https://github.com/MTES-MCT/ecobalyse/pull/873#pullrequestreview-2527370075

chore: update trim api parameter ordering.

---

.github/workflows/create_release.yml

[context](https://github.com/MTES-MCT/ecobalyse/pull/892/files#r1913313528)

refactor: improve YAML gh action legibility.

---

public/data/textile/examples.json

[Notion card](https://www.notion.so/Modifier-le-seuil-du-nombre-de-refs-fast-fashion-dc88f191a0804b17b56106d438398c24)

chore(data): update fast fashion examples nb of references.

---

public/data/food/ingredients.json

> _Describe the problem you're trying to solve, the reason why you are creating this pull request. Provide a link to the Notion card if any._
There are doubts on the impacts of the lamb
https://www.notion.so/Masquer-les-agneaux-UE-et-hors-UE-197b056852fc8051b470e7c9d6413b5c
> _Explain the solution that this PR implements to solve the problem above._
hide the lamb for now
Check there are no imported lamb (UE, hors UE)

chore: doubts on the lamb, hide it for now

---

src/Data/Component.elm
src/Data/Object/Query.elm
src/Page/Object.elm
src/Page/Textile.elm
src/Views/Component.elm
tests/Data/ComponentTest.elm

feat(object,ui): allow set a custom component name (fixes #980)

---

src/Page/Food.elm

fix(food,ui): fix food transform processes list not scoped

---

src/Data/Bookmark.elm
src/Main.elm
src/Page/Food.elm
src/Page/Object.elm
src/Page/Textile.elm
src/Request/Version.elm
src/Views/Bookmark.elm
src/Views/Comparator.elm
src/Views/Page.elm
src/Views/Version.elm
styles.scss
tests/Request/VersionTest.elm

feat: store and render app version along bookmarks

---

src/Data/Component.elm
tests/Data/ComponentTest.elm

fix(object,ui): fix string representation of custom component items

---

src/Data/Bookmark.elm
src/Data/Component.elm
src/Data/Object/Query.elm
src/Data/Textile/Query.elm
src/Page/Object.elm
src/Page/Textile.elm
src/Views/Component.elm
tests/Data/ComponentTest.elm

feat(object,ui): allow multiple component instances

---

src/Data/Common/EncodeUtils.elm
src/Data/Component.elm
src/Data/Food/Query.elm
src/Data/Textile/Inputs.elm
src/Data/Textile/Query.elm
src/Views/ImpactTabs.elm
tests/Data/ComponentTest.elm

feat(object): render lifecycle stage impacts data

---

Pipfile
Pipfile.lock

see https://github.com/MTES-MCT/ecobalyse/security/dependabot/62

chore: upgrade django to 5.1.8

---

.env.sample
README.md
index.js
server.js
src/Data/Component.elm
src/Data/Scope.elm
src/Data/Session.elm
src/Main.elm
src/Page/Admin.elm
src/Page/Auth.elm
src/Request/Component.elm
src/Route.elm
src/Views/Component.elm
src/Views/Icon.elm
src/Views/Page.elm

refs https://github.com/MTES-MCT/ecobalyse-data/pull/65

feat: minimalistic component back-office

---

src/Data/Process.elm
tests/Data/ComponentTest.elm

chore: create local test component data

---

review/src/ReviewConfig.elm
src/Main.elm
src/Page/Explore.elm
src/Page/Home.elm
src/Views/Page.elm

chore: update home page

---

src/Data/Common/DecodeUtils.elm
src/Data/Process.elm
src/Page/Explore/Processes.elm
src/Page/Food.elm

fix(food,ui): render ingredient technical process name tooltip

---

src/Page/Admin.elm
src/Request/Component.elm
src/Views/Icon.elm
src/Views/Modal.elm

feat(bo): allow duplicating components

---

src/Page/Admin.elm

feat(bo): add a button to export components json db

---

.github/workflows/node.js.yml
jest-puppeteer.config.js
package-lock.json
package.json
tests/setup-version-fixture.sh
tests/versions.spec.js

chore: test versions

---

public/data/object/components.json
public/data/object/examples.json
public/data/processes.json
tests/Data/Object/SimulatorTest.elm

chore: cleanup object

---

src/Page/Auth.elm

Users may get a disturbing "Unauthorized" error notification when clicking a previously used magic link, this is because the backend API responds with a generic 401 when a magic link token has already been consumed. 
In this specific situation and if the user is already signed in, don't render any error message.
The patch also automatically discards auth session data when the server is desynchronized (eg. the user doesn't exist anymore in the db, which happens when a new review app is deployed or locally during testing)
Also, I didn't see a point notifying the user that the link has already been used, as he's already signed in anyway.

fix: handle reusing outdated magic links.

---

playwright.config.js

This is an attempt at fixing playwright test failures on retries

chore: improve playwright test config

---

src/Data/Gitbook.elm

fix(textile): update docs link for ennobling.

---

openapi.yaml

context: https://mattermost.incubateur.net/fabnum-mte/pl/y4uf5n74xb8sdniixxgp3wi1de

fix(api): fix typo in printing api docs

---

src/Page/Explore.elm

fix(ui): don't scrolltop on explorer modal closed

---

public/data/impacts.json

unit for wtu should be `m3 eq` not `m3`

chore: wtu m3 eq

---

public/data/textile/products.json

chore: update default trims following feedback

---

.env.sample
index.js
lib/crypto.js
lib/posthog.js
package.json
server.js
tests/lib/http.spec.js
tests/lib/posthog.spec.js
tests/rate-limiting.spec.js

The requests made to the API weren't logged at all on Posthog. This patch fixes that and add a few more useful data to the events.

fix: fix api requests logging

---

src/Server.elm
tests/server.spec.js

fix(api): filter food api transform processes

---

openapi.yaml

fix(api): fix textile api product field docs

---

openapi.yaml
src/Data/Split.elm
src/Data/Textile/Printing.elm
src/Page/Api.elm
src/Views/Textile/Step.elm
tests/Data/SplitTest.elm
tests/server.spec.js

fix(textile)!: limit printing surface ratio to 80% max

---

package-lock.json
package.json

chore: upgrade posthog deps

---

public/data/food/ingredients.json
tests/Data/Food/RecipeTest.elm

See https://github.com/MTES-MCT/ecobalyse-data/pull/124

fix: Fixed scenarios

---

public/data/food/ingredients.json

See https://github.com/MTES-MCT/ecobalyse-data/pull/128

chore: fixed cocoa butter

---

e2e/object-simulator.spec.js
public/data/object/components.json

Components list is not relevant for Object scope
Create new list of components

chore:  update components list for Object

---

bin/scalingo_api.py

We want a way to get usage metrics for versions.
Improve the scalingo CLI script.
```python
uv run bin/scalingo_api.py log-archives
```
You should have an output like this one:
```
{
'v1.1.0': 170,
'v1.2.0': 29,
'v1.3.0': 29,
'v1.3.1': 41,
'v1.3.2': 29,
'v2.0.0': 19,
'v2.1.1': 29,
'v2.2.0': 12,
'v2.3.0': 47,
'v2.4.0': 92,
'v2.5.0': 66,
'v2.6.0': 88,
'v2.7.0': 37,
'v2.7.0-api': 42,
'v2.7.1': 37,
'v3.0.0': 80,
'v3.0.0-api': 1,
'v3.1.0': 82,
'v4.0.0': 76,
'v4.0.0-api': 35067,
'v4.0.1': 365,
'v4.0.1-api': 18663,
'v5.0.0': 57,
'v5.0.0-api': 10,
'v5.0.1': 533,
'v5.0.1-api': 2156,
'v6.1.0': 31,
'v6.1.1': 1991,
'v6.1.1-api': 283,
'v7.0.0': 3314,
'v7.0.0-api': 443293,
'v7.1.0': 1272,
'v7.1.0-api': 752288,
'v8.0.0-api': 1
}
```

chore: add versions stats to scalingo cli
