- .gitignore
- package-lock.json
- package.json
- server.js
- src/Data/Inputs.elm
- src/Data/Material.elm
- src/Data/Product.elm
- src/Main.elm
- src/Page/Simulator.elm
- src/Route.elm
- src/Server.elm
- src/Views/Summary.elm
This patch is mainly an experimental investigation at this point, it may never be merged, and that's fine.
As the whole application logic + data sources currently reside in the Elm codebase, and users have expressed a need for an HTTP api exposing an equivalent service to what the [Web application](https://mtes-mct.github.io/wikicarbone/#/simulator) currently provides, I'm experimenting creating one reusing that existing code. (Translation: No, I don't really want to rewrite the whole computation logic in js or Python)
> Expose the simplest node+Elm HTTP API

- src/Data/LifeCycle.elm
- src/Data/Step.elm
- src/Views/Step.elm
- src/Views/Summary.elm
- src/Views/Transport.elm
[User Story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=af2332265058414da4bd3aa4d381ed5f&p=e78a94318c4743c4a84a532a692506a6)
Note: the production API server doesn't reflect this patch, though you can inspect the generated `data/dump-presets.json` which should be available online [here](https://wikicarbone.beta.gouv.fr/branches/attach-step-transport-process-info/data/dump-presets.json) once the PR is built.
> Expose step transport processes to both UI and API.

- .github/workflows/node.js.yml
- src/Data/Formula.elm
- src/Data/Sample.elm
- src/Data/Simulator.elm
- src/Page/Examples.elm
- src/Page/Home.elm
- tests/Data/FormulaTest.elm
- tests/Data/SimulatorTest.elm
[User Story](https://www.notion.so/Bug-Ne-pas-multiplier-par-la-masse-pour-l-impact-de-l-tape-de-confection-506a72a2075e4b548dac887f18fc14a6)
- Once built, this branch will be testable at  https://wikicarbone.beta.gouv.fr/branches/fix-making-step-impact/
- API can't be deployed to test this patch yet
> Fix making step energy & co2 impact computations.

- public/data/openapi.yaml
- src/Data/Inputs.elm
- src/Server.elm
- tests/Data/InputsTest.elm
In the UI, the first step's country is constrained by the material used: it's always going to be the material's default country.
This also needs to be the case when going through the API, as changing the country would lead to incorrect results (the data for the weaving and knitting is only provided for a single country for a given material).
> Use the material's default country even when using the API

- .proxyrc.js
- .proxyrc.json
After upgrading Parcel to 2.3.1 (before: 2.2.1), local dev API server proxy stopped working for obscure reasons. Switching to using a `.proxyrc.json` instead of a `.proxyrc.js` one using the very same configuration solves the issue.
> Fix .proxyrc behavior after parcel upgrade to 2.3.1.

- src/Page/Simulator.elm
- src/Views/Button.elm
- src/Views/Step.elm
The Gitbook Markdown custom syntax is way too cumbersome to parse, I'm switching all documentation modals to plain old links.
> Drop documentation modals.

- src/Data/Inputs.elm
- tests/Data/InputsTest.elm
[User Story](https://www.notion.so/BUG-Au-changement-de-produit-les-masses-d-tapes-ne-sont-pas-mises-jour-1b20a23abe0c44468bf4629797b5d0cf)
> Apply default product mass on product change.

- src/Page/Food/Simulator.elm
We can't track JSON db download progress because elm-http [doesn't allow tracking with task based requests](https://package.elm-lang.org/packages/elm/http/latest/Http#task), so [neither does remotedata-http](https://github.com/ohanhi/remotedata-http/issues/7).
So we're left with just a rolling spinner materializing the (long) loading stage, which is still better than nothing.
> Add a loading spinner to Food PoC page.

- src/Page/Food/Simulator.elm
I'm finding entering grams much more natural than kilograms for ingredients mass. Thoughts?
Edit: validated with @paulboosz over Mattermost that we can safely round ingredient weight values provided in kg by agribalyse to grams.
> [food] Use grams as the unit to use for ingredient mass inputs.

- src/Data/Food/Product.elm
- src/Page/Food/Simulator.elm
An original recipe's final weight is always 1kg (eaten), so the impact "per kg" and "total" on an original recipe should always be the same.
When displaying an original recipe, don't display the "total impact" as it's redundant.
https://user-images.githubusercontent.com/167767/191928563-067427af-da2c-4fa8-b238-3f6fddeabd23.mov
Also display the final weight after the "at consumer" step
> Fix final weight calculation (an original recipe's final weight is always 1kg)

- src/Data/Food/Builder/Recipe.elm
- src/Data/Impact.elm
- src/Page/Food/Builder.elm
- src/Views/Comparator.elm
- src/Views/Format.elm
- tests/Data/Food/Builder/RecipeTest.elm
- tests/Data/ImpactTest.elm
[User Story](https://www.notion.so/Ne-pas-prendre-en-compte-l-emballage-dans-la-masse-permettant-de-calculer-le-score-kg-4dad80072fa34aaf8285351033144ed5)
> Exclude packaging mass from impacts/kg of product computations.

- openapi.yaml
- src/Data/Food/Builder/Query.elm
- src/Data/Food/Builder/Recipe.elm
- src/Data/Food/Ingredient.elm
- src/Page/Food/Builder.elm
- src/Server/Query.elm
- styles.scss
- tests/Data/Food/Builder/RecipeTest.elm
- tests/e2e-food.json
- tests/server.spec.js
[user story](https://www.notion.so/fd0068a7db8348c584cd53a3eea399f2?v=90c1a9d44ff845c090b6f491065ba2ef&p=2786364aac184ee88a14b480045ebe61&pm=s)
Follows on #220 by allowing the disabling of the transport by plane for category 4 ingredients (default origin by plane) even from their default origin.
> Allow disabling the transport by plane even from default origin

- openapi.yaml
- src/Data/Food/Builder/Query.elm
- src/Data/Food/Builder/Recipe.elm
- src/Page/Food/Builder.elm
- src/Server/Query.elm
- tests/Data/Food/Builder/RecipeTest.elm
- tests/Server/RouteTest.elm
- tests/e2e-food.json
- tests/server.spec.js
After some discussion on mattermost, we decided that it made more sense to just leave an value empty in the API instead of explicitly using `default`.
> Remove `default` from api

- src/Data/Food/Builder/Query.elm
- src/Page/Food/Builder.elm
Requested in [this card](https://www.notion.so/CORRECTIFS-ACV-Pr-parer-l-introduction-des-impacts-n-gatifs-IAE-diversit-interface-mod-le-de-cd6e6379e85a48c5baa4584e43857e0b):
> Retour aux % par défaut lorsque l’on change d’ingrédient. Aujourd’hui, on bascule sur les % par défaut lorsque l’on passe de bio à “pas bio”. En revanche, si les % ont bougé, ils sont conservés lorsque l’on change le choix d’ingrédient. Il faudrait idéalement qu’ils reviennent sur le % par défaut du nouvel ingrédient choisi.
> Reset bonuses when swapping ingredients.

- public/data/impacts.json
[User Story](https://www.notion.so/Correction-bug-d-affichage-chiffre-100-microPts-ou-1000-microPts-a389211c063e42eeb76e77c659d412ce)
TL;DR: `µPts d'impact` was too long and broke some layout on smaller viewports. `µPts` is enough.
> Shorten impact unit.

- src/Data/Textile/Product.elm
- src/Data/Textile/Simulator.elm
- src/Data/Textile/Step.elm
- src/Views/Textile/Step.elm
- tests/Data/Textile/ProductTest.elm
[user story](https://www.notion.so/Tricotage-adapter-taux-de-perte-8c6226030a734dfc90b3e17216b29b0b) : it was always the default product's knitting process' waste that was used, instead of the selected one's.
> Use the selected knitting process' waste

- src/Data/Impact.elm
- src/Page/Food/Builder.elm
- src/Views/Bookmark.elm
- src/Views/CardTabs.elm
- src/Views/Table.elm
- styles.scss
This is the first part of [this card](https://www.notion.so/Harmoniser-la-pr-sentation-du-d-tail-des-postes-entre-textile-et-alimentaire-c7530e3369e64dabaed7df8026bea733) (remaining work will be to add support for ecoscore to Textile — which should happen separately — and use the blocks provided by this patch to render impacts information tabs the same way we do for food here)
> Spread food impact information over three tabs in the sidebar.

- src/Data/Bookmark.elm
- src/Data/Food/Builder/Db.elm
- src/Data/Food/Builder/Recipe.elm
- src/Data/Food/Preparation.elm
- src/Data/Session.elm
- src/Data/Transport.elm
- src/Main.elm
- src/Page/Explore.elm
- src/Page/Food/Builder.elm
- src/Request/Food/BuilderDb.elm
- src/Views/Comparator.elm
- tests/Data/Food/PreparationTest.elm
More refactoring: 
- ~~[ ] split Textile.Db.(impacts|countries|transports) into Common.Db to be reused by Textile and Food databases~~ this is not possible because the countries are actually "Textile countries" with textile processes for electricity and stuff... so we would also need to load the textile processes, which makes less sense... or split the "textile part" of the countries data in another db... we'll see that in another PR ;)
> Store the food builder db in the session as a WebData (no more Db.empty)

- src/Main.elm
Parcel's hot module reloading needs the NavKey to always be in the same place. With the new way to load the session (sometimes a partial session, without the db, sometimes a full session with the db loaded), the nav key "changes" place.
The easy and naive fix is to duplicate the NavKey in the model.
> Fix hot module reloading by keeping the NavKey in the main model

- src/Data/Textile/Step.elm
- src/Views/Textile/Step.elm
[Bug report](https://www.notion.so/Distance-transport-1f160ec79d084fb98eaa92453411e51b)
This patch disables the air transport ratio rangeslider when the Making step takes place in France (and is then shipped to France by default). There's no real world situations where clothes are transported by plane from France to France.
> Disallow setting air transport from France at the Making step.

- src/Data/Github.elm
- src/Page/Changelog.elm
The changelog page is broken because some of the github API response author object fields are missing (ingredient editor commit data, cc @ccomb). Note that it would be nice if the ingredient editor could have an associated avatar image, but I'm not sure what would be required for that (we don't want to create a github account for that). Gravatar maybe? Anyway that's unrelated to this patch.
> Fix bogus github changelog decoding with ingredient editor.

- data/docker/Dockerfile
- data/docker/requirements.txt
- data/setup.py
The docker entrypoint was installing bw_projects, thus requiring network and slowing down startup.
Installation of bw_projects has been moved to the Dockerfile for faster make commands and no network dependency.
> Faster make commands

- .env.sample
- README.md
- index.js
- server.js
@magopian Not sure if I prefer this or your approach in #423, which seems more robust 🤔
If we go the #423 route, ideally we would have a `Maybe Matomo` so we could disable stats in dev and only have them in production when env vars are properly set. What do you think?
> Improve docs and checks for required env vars.

- package-lock.json
- package.json
- server.js
Replaces #428
Note: no need to update the README as this patch actually implements what is documented there: *le serveur de développement node chargera les variables en conséquences* :)
> Rely on dotenv to read environment variables.

- src/Data/Textile/Inputs.elm
- tests/Data/Textile/InputsTest.elm
A very simple enhancement and a small bugfix. 
@magopian I was also thinking of searching into the category name as well, because atm if you search for "polo" it shows no results, while we might want to expose t-shirt examples from the *t-shirt/polo* category as a starting point… what do you think?
> Improve textile examples autocomplete.

- openapi.yaml
Quick fix, missing `fabricProcess` parameter in the API example
> Add the missing "fabricProcess" parameter to the API example

- src/Page/Food.elm
The auto-DOM-scrolling strategy when adding or updating examples/ingredients in the Food calculator makes it really hard and counter-intuitive to use. This patch removes all related code so the behavior is back to normal (no autoscroll at all).
> Remove confusing DOM element autofocusing behavior.

- openapi.yaml
same as https://github.com/MTES-MCT/ecobalyse/pull/462 but merge into master
Fix
> add-missing-fabricProcess-api-example

- src/Data/Bookmark.elm
- src/Data/Session.elm
- src/Data/Textile/ExampleProduct.elm
- src/Data/Textile/Inputs.elm
- src/Data/Textile/LifeCycle.elm
- src/Data/Textile/Query.elm
- src/Data/Textile/Simulator.elm
- src/Main.elm
- src/Page/Explore/TextileProducts.elm
- src/Page/Textile/Simulator.elm
- src/Route.elm
- src/Server.elm
- src/Server/Query.elm
- src/Server/Route.elm
- src/Views/Bookmark.elm
- src/Views/Textile/Step.elm
- tests/Data/Textile/InputsTest.elm
- tests/Data/Textile/LifeCycleTest.elm
- tests/Data/Textile/QueryTest.elm
- tests/Data/Textile/SimulatorTest.elm
- tests/Server/RouteTest.elm
[Tech Debt] This patch splits the textile `Query` stuff from `Inputs` and moves it to a new dedicated module. This avoids an annoying cycling dependency issue when importing the static `Db` in the `Inputs` module. Also this matches what is done for Food with the `Recipe` and `Query` modules.
> Split the textile inputs & query modules.

- src/Data/Food/Query.elm
- src/Main.elm
- src/Page/Food.elm
- tests/Data/Textile/QueryTest.elm
- tests/Server/RouteTest.elm
- tests/Server/ServerTest.elm
- tests/server.spec.js
[User Story](https://www.notion.so/Ajouter-une-v-rification-de-validit-des-exemples-de-produits-a722f2317ee142f2a3bb668c901b1594)
The idea is to fail the test suite on any invalid product example so we can be notified about it.
Sample failure output example:
> Fail test suite when product examples are invalid.

- openapi.yaml
- src/Main.elm
- src/Page/Api.elm
- src/Page/Explore.elm
- src/Page/Home.elm
- src/Route.elm
- src/Views/Page.elm
This is part of the ongoing v2 work ([card](https://www.notion.so/Pr-paration-mise-en-ligne-V2Beta-textile-04bc56c5436e407ab093469250f15a52)). Note to the curious reader: these will be reinstated later on.
> Temporarily hide login/out & food links, remove food API docs.

- styles.scss
Hi, there was a little style issue with the `selector-example`:
After:
> Fix style issue with the `selector-example`

- index.js
- openapi.yaml
- src/Data/Session.elm
- src/Data/User.elm
- src/Page/Api.elm
- src/Page/Auth.elm
- src/Views/Alert.elm
This patch stores the user profile information in the session store, so we can pass it to the rapidoc component in the Api page, allowing to access detailed impacts when authenticated on the website.
> Use API token in OpenAPI interactive documentation page.

- package-lock.json
- package.json
- server.js
Some benchmarks:
20 requests per second:
40 requests per second:
50 requests per second:
> Memoize processes on token

- src/Data/Textile/Simulator.elm
This patch temporarily reverts #577 because we must not land code changing computation results in production until next official release.
> Revert waste computation fix temporarily (refs #577)

- backend/authentication/models.py
- backend/backend/settings.py
- backend/templates/admin/textile/example/change_list.html
- backend/templates/admin/textile/example/from_json.html
- backend/textile/admin.py
- backend/textile/choices.py
- backend/textile/init.py
- backend/textile/models.py
- backend/update.sh
The staging branch already contains code to manage [textile](https://github.com/MTES-MCT/ecobalyse/tree/staging/backend/textile) data on the backend, but it is disabled.
This PR adds improvements to flush the work already done. It is still disabled but reverting the last commit allows to enable it again. I'll enable it in another branch and then work on something else.
- Store and modify textile json in the backend
- naming and fieldsets improvements on the forms
- allow to create an example by copying example json as is, from the frontend to the backend
> Data in backend

- .github/workflows/node.js.yml
- README.md
Currently, there is a silent error in the CI due to the absence of `gettext`.
Install `gettext` in the CI build.
> Add missing `gettext` in CI build

- .github/workflows/node.js.yml
- README.md
- backend/authentication/tests.py
- package.json
- Backend tests are not run in the CI
- `npm` command/scripts naming is inconsistent between the front and the back
- We display a stack track in the Django tests and don't check for the exact exception thrown
Run the tests in the CI by adding an entry into the `node.js.yml` file and rename the inconsistent commands in `package.json`.
As the authenticate can fail for many reasons (expired token, user missing) we test that it's the appropriate exception that is raised in the python logs and silent the output at the same time.
- The CI should pass
- `npm test`, `start:dev` and `npm test:server-ci` should work as usual
> Fix backend tests

- src/Views/Page.elm
[User story](https://www.notion.so/Dans-l-explorateur-rebasculer-par-d-faut-sur-les-exemples-4b32805fc18e45f78ddd7d2651579d7d?d=23567da9dc644c40bb2ea9ffa6b99917)
> Set textile explorer default tab to product examples.

- .prettierignore
Prettier formats the upcoming CHANGELOG.md automatically and breaks the automatic release.
Add `*.md` file to `.prettierignore`
> chore: dont't format `*.md` files

- .env.sample
- README.md
- backend/backend/settings.py
> docs: enhance README

- compute-aggregated.js
`npm run processes:build` fails as it tries to export legacy fake details files.
Remove fake details export.
> fix: don't export legacy fake details

- src/Data/Textile/Formula.elm
- src/Data/Textile/Inputs.elm
- src/Data/Textile/Material/Spinning.elm
- src/Data/Textile/Step.elm
- src/Data/Unit.elm
- src/Page/Explore/TextileProducts.elm
- src/Server/Query.elm
- src/Views/Format.elm
- src/Views/RangeSlider.elm
- tests/Data/UnitTest.elm
This patch partially address [this user story](https://www.notion.so/Bug-API-52a9084b9f404f1faf14b9d27a2339cf), most notably the bug regarding the `yarnSize` API param parsing. Yes at some point we'll want one single card per bug.
```elm
> import Json.Decode as D
> import Data.Unit as U
> "27.04"|>D.decodeString U.decodeYarnSize
Err (Failure ("Expecting an INT") <internals>)
: Result D.Error U.YarnSize
> "27"|>D.decodeString U.decodeYarnSize
Ok (Quantity 27000) : Result D.Error U.YarnSize
```
Yarn size cannot be expressed as floats while they should.
Accept a yarn size to be expressed as a float.
> fix: yarnSize API param wasn't parsed when provided as float.

- .github/actions/scalingo-cli/action.yml
- .github/workflows/score_history.yml
Currently we use a direct connection to the PostgreSQL exposed publicly. As we want to close the public access, we have to find another way to connect to PG.
Use the scalingo CLI to create a tunnel between Github Actions and PG.
I am using a personal access token for the scalingo API access. We should change it as soon as we got the new `dev@ecobalyse.beta.gouv.fr` email and service account on Scalingo.
The `score_history` action should not fail.
> chore: connect to PG using tunnel

- src/Data/Textile/Step.elm
[User story](https://www.notion.so/Arrondir-le-nombre-Dtex-dans-l-UI-Web-a5d957cc6acb4940a7c95d268ea7ac51)
> fix(ui): Round Dtex number in the web UI.

- src/Page/Textile.elm
The patch renames the *Mode avancé* tab to *Mode pédagogique* ([user story](https://www.notion.so/Renommer-l-onglet-Mode-avanc-en-Mode-p-dagogique-d98a9845ff29489a991a509ebcc50dc6))
> chore(ui): Rename advanced tab to learning tab.

- .github/workflows/release-please.yml
`release-please` tries to encrypt the files even if no release was created.
Add the missing `if`.
After the merge on master, the next release-please build should be ok.
> fix: add missing condition in `release-please` workflow

- .github/workflows/release-please.yml
- Pipfile
- Pipfile.lock
- bin/get-tag-for-commit.py
- bin/update-version.sh
- src/Main.elm
- src/Request/Version.elm
- src/Views/Page.elm
- tests/Request/VersionTest.elm
We want to be able to know the current tagged version of the app on the website. It will allow people doing computations to know the version number they are using (and later on, come back to this version when the versioning system will be online).
When deploying on Scalingo, call the Github API to get the tag corresponding to the current commit, if any. If we find a tag, we display it (and link to the release page) if not, the behavior is the same as before (display the commit number and a link to this commit on Github).
We are using calls to the public Github API to get the tag corresponding to the commit number. There is a rate limit of 60 calls per hour to the public Github API. We may want to get an app token to avoid such problems.
If you have one, you can set the …
> feat: display current version in the footer

- .buildpacks
- .github/workflows/node.js.yml
- .github/workflows/score_history.yml
- bin/checkout-ecobalyse-private-branch.sh
- bin/extract-data-branch-from-pr.sh
- buildpack-run.sh
We need a way to be able to test a PR with a specific branch of the `ecobalyse-private` repo.
Parse the body of the PR for a line with `ecobalyse_data: <branch_name>` pattern. When deploying on scalingo, check if the current deployed commit is part of an opened PR and check if there is a `ecobalyse_data: <branch_name>` line. If so, we checkout the corresponding branch of `ecobalyse-private`.
We do the same when running the tests and score_history in the Github Workflows.
Create a branch in the `ecobalyse-private`, create a PR (or use this one) with the specific line. Check that the app contains the data of the `ecobalyse-private` branch.
ecobalyse_data: organic_tomato
> chore: provide a way to synchronise a branch of `ecobalyse-private` with a PR

- .github/workflows/release-please.yml
Release please build is failing because the `ECOBALYSE_DATA_DIR` is missing.
Add the env variable to the github workflow.
Merge to master and rerun the release-build workflow that should be green.
> fix: add ecobalyse-private to release please

- bin/update-version.sh
As our versions depend on a private repository, we may need later on to be sure what commit hash of this private repository was used to build the specific version. For example, it will be useful for the version history system.
Just add an entry in the `public/version.json` file containing the hash of the private repository.
We don't use it/decode it on the elm side as it's not useful for the end user.
Once deployed go to https://ecobalyse-pr686.osc-fr1.scalingo.io/version.json and check that `dataDirHash` key is present and that the sha is the same than the latest commit on https://github.com/MTES-MCT/ecobalyse-private
ecobalyse_data: test1
> chore: keep track of data-dir hash

- data/notebooks/explore.py
There is only one download button on the brightway explorer, to download the list of processes that appears in the search result.
This PR improves the button to include the same three columns as seen in the search result.
It also add two download buttons in the Analysis tab which allows to download the top processes and emissions as CSV.
It also reorders the amount and score columns in the analysis
> feat: Brightway explorer download buttons

- src/Request/Version.elm
With the upcoming versioning system https://github.com/MTES-MCT/ecobalyse/pull/627 we will need to serve the app from a relative path like `/versions`, so we should serve the version file from a relative path instead of the root path.
Use relative path when doing the HTTP request.
Go to https://ecobalyse-pr693.osc-fr1.scalingo.io/ and the version at the bottom should still display the latest commit of this branch.
> chore: serve version file with relative path

- .github/workflows/score_history.yml
- packages/python/ecobalyse/ecobalyse/github.py
The CI build fails on master because the `run` parameter is missing in the `score_history` workflow.
We add the missing parameter.
A bug in the python code was fixed at the same time when a PR is opened without a body.
Run the `score_history` workflow dispatch by hand in the Github Actions.
> fix: add missing run command for score history [score_history]

- Pipfile
- Pipfile.lock
- README.md
- bin/build-specific-app-version.sh
- bin/patch_files_for_versions_compat.py
- packages/python/ecobalyse/ecobalyse/0001-feat-patch-homepage-link-and-inject-and-inject-versi.patch
- packages/python/ecobalyse/ecobalyse/patch_files.py
- packages/python/ecobalyse/ecobalyse/tests/test_patch_old_versions.py
We are using a combination of bash and sed commands to patch the files and it's not reliable: it breaks on Mac OS X and it is not testable.
Replace critical bash code with tested python code.
I've introduced [Typer](https://typer.tiangolo.com/) to manage the CLI program. It uses Python types to parse arguments and provides a lot of features out of the box. You can run the help command for example to see by yourself:
pipenv run python ./bin/patch_files_for_versions_compat.py --help
Be sure to run `pipenv install` first.
Building a specific version with `pipenv run ./bin/build-specific-app-version.sh v1.3.2 3531c73f23a1eb6f1fc6b9c256a5344742230fcf` for example should still work as expected.
> refactor: use python to patch files

- .github/workflows/node.js.yml
- .github/workflows/score_history.yml
We may face rate limiting issues with the github API when running workflows because we are not using any Github token.
Use the automatically generated token in github actions to call the public API.
The Github worklows should still be green.
> fix: add github token to worklows

- elm.json
- src/Page/Explore/Countries.elm
- src/Page/Explore/FoodExamples.elm
- src/Page/Explore/FoodIngredients.elm
- src/Page/Explore/FoodProcesses.elm
- src/Page/Explore/Impacts.elm
- src/Page/Explore/Table.elm
- src/Page/Explore/TextileExamples.elm
- src/Page/Explore/TextileMaterials.elm
- src/Page/Explore/TextileProcesses.elm
- src/Page/Explore/TextileProducts.elm
[user story](https://www.notion.so/Permettre-de-t-l-charger-en-csv-excel-les-donn-es-de-l-explorateur-a459d3be30cc44cb8977788073768df0)
Users want to be able to download the explorer data as CSV, so they can inspect and use them in their favorite software like Excel or Numbers.
This patch adds a button to download explorer data as CSV on every tab, at the bottom right of the data table, for food and textile data.
Click on the download buttons and open the CSV file in your preffered CSV viewer.
> feat: allow downloading explorer data as CSV.

- src/Data/Food/Db.elm
- src/Data/Food/WellKnown.elm
- src/Data/Session.elm
- src/Data/Textile/Db.elm
- src/Data/Textile/WellKnown.elm
- src/Main.elm
- src/Page/Auth.elm
- src/Static/Db.elm
Sometimes when processes data are updated server side, the locally cached client data are desynced, which triggers weird issues — most notably in the comparator with missing chart segments, those corresponding to missing data or linked objects.
This patch removes all use of the processes data cached in localStorage, and loads detailed data on client app start when authenticated. That way, we're always sure to start the client app with the latest available data from the server.
Very hard to simulate data changed from the server while a locally cached previous version of it lives in memory. I suspect you'll have to trust me on this one.
> fix: broken comparator charts on desynced cache data.

- src/Request/Version.elm
- src/Views/Page.elm
This patch removes the `Unreleased` version selector entry when the app is a tagged release.
> fix(ui): Hide unreleased entry in production version selector.

- server.js
When using the API in production, you have no obvious way to be certain what's the precise app version you're using, as there's no version in the endpoint url nor in the result payloads.
Expose the app version in the root endpoint, where the openapi docs reside.
```
$ curl https://ecobalyse-pr726.osc-fr1.scalingo.io/api | jq .version
"2.1.1"
```
> feat: add app version to openapi docs in the root endpoint.

- lib/instrument.js
- package-lock.json
- package.json
- server.js
We have `[server] [Sentry] express is not instrumented. This is likely because you required/imported express before calling Sentry.init()` log errors which is fixed by this patch — which follows the [official integration guide](https://docs.sentry.io/platforms/javascript/guides/express/).
> fix: ensure express app is properly monitored by Sentry.

- data/docker/entrypoint.sh
- data/setup.py
no need for a setup.py as it's not distributed as a package. We just need to import it.
It allows faster and offline docker entrypoint where we don't install the local package
> chore: remove unneeded python package

- packages/python/ecobalyse/ecobalyse/github.py
- packages/python/ecobalyse/ecobalyse/tests/test_data_branch.py
Currently, we are checking for `ecobalyse_data` in the content of a PR to synchronize withe the `ecobalyse-private` repo. For consistency, check for `ecobalyse-private`.
Github token was changed to my personal token to avoid 403 responses. We may need to use an app token at some point.
Tests have been moved to the package directory for consistency.
Merge this PR in a PR requiring a different `ecobalyse-private` branch and check that everything is working as expected.
> fix(ci): check for ecobalyse-private when extracting the branch name

- src/Page/Explore/FoodProcesses.elm
The `source identifier` column is a duplicate of the `identifier` and can be removed
> refactor: Removed duplicate identifier column in the food explorer

- data/README.md
- data/notebooks/explore.py
- public/data/textile/processes.json
- src/Data/Food/Process.elm
- src/Data/Textile/Process.elm
- src/Page/Explore/FoodProcesses.elm
- src/Page/Explore/TextileProcesses.elm
- tests/Data/Textile/FormulaTest.elm
[Story](https://www.notion.so/4f0841edbc29408eb147558e53fe2acd?v=40d0d544eb8e4c03891da1f9aad8b6cd&p=8001e835e8024b45a7014c4cb2e5b9e3&pm=s)
ecobalyse-private: textile_explorer
> feat: displayName in the textile explorer, reordered columns

- src/Data/Textile/Inputs.elm
- src/Data/Textile/Query.elm
- src/Data/Unit.elm
This patch fixes missing JSON encoding of this parameter and update inputs string representation to include it as well. It also fixes an issue where two saved simulations could be highlighted while only one was actually selected (because the string serialization was used to check the highlight status).
> fix: encode physicalDurability parameter.

- package-lock.json
- package.json
Closes #739
Closes #740
Closes #741 
Closes #742
Note: it would be nice to find a way to allow dependabot builds to succeed, so we don't have to do these PR manually.
> chore: upgrade deps (2024-09-12)

- README.md
- openapi.yaml
- server.js
While we introduced the `ENABLE_FOOD_SECTION` env var to hide or show the Food section, associated menus and links, we hide the API docs for Food completely and there's no current way to access these API docs. 
This patch checks for the value of the `ENABLE_FOOD_SECTION` var and filter the openapi docs appropriately.
Check that the API docs for food are available for this review app.
> chore: render food api docs conditionally from env.

- .env.sample
- README.md
- bin/build-specific-app-version.sh
- index.js
- lib/instrument.js
- scalingo.json
Production and review app errors are mix and matched in Sentry.
[Notion card](https://www.notion.so/Ne-loguer-les-v-nements-Sentry-qu-en-production-43f188ca8a624f08b6b7c7fd8e31254d)
Use a different environment in Sentry for production and review-apps errors.
I've introduced a new file `scalingo.json` used to configure review apps https://doc.scalingo.com/platform/app/review-apps#run-a-task-after-each-deployment-of-a-review-app
I have CORS issue with the envelope call on the review-app without knowing why. Could be a server config/version issue cf. https://github.com/getsentry/sentry/issues/24637
Clicking on the footer should throw an error (the code will be removed before merging).
> chore: filter sentry errors by env

- data/Makefile
- data/docker/entrypoint.sh
Bug : 
Fix :
- The previous  chown command in the Dockerfile is setting ownership to user ID 1000, but the error message suggests the container is running as user ID 1001. -> use the actual jovyan user ID in the container
- clear the npm cache before running any npm commands
> chore: fix npm error when make_export_food

- .github/workflows/node.js.yml
This is an attempt at fixing failing github action CI builds at the Python setup step.
https://github.com/actions/cache/blob/main/examples.md#python---pipenv
> fix: fix github CI python build setup.

- src/Data/Textile/Query.elm
- src/Data/Unit.elm
- src/Server.elm
- src/Server/Query.elm
- src/Server/Route.elm
- tests/Server/RouteTest.elm
- tests/server.spec.js
~~Funnily enough, while we were thinking there wasn't any validation applied to some input POST parameters in the API, it was in fact our unit test env which was unable to execute these tests, because it didn't have access to the native JSON body to execute the correct assertions. Validation was working in e2e tests just fine… I should probably have spotted that earlier.~~
Edit: There actually wasn't any validation performed on some optional parameters passed as a JSON  body to POST requests, because we were using the infamous `Json.Decode.maybe` decoder which fallbacks to returning `Nothing` instead of a failure in case the decoded value is invalid. This patch leverages [Json.Decode.Extra.optionalField](https://package.elm-lang.org/packages/elm-community/json-extra/latest/Json-Decode-Extr …
> fix: stricter validation of POST json body passed to the textile API.

- src/Data/Common/DecodeUtils.elm
- src/Data/Food/Process.elm
- src/Data/Food/Query.elm
- src/Data/Textile/Query.elm
Follow-up to #760, propagating the fix for the Food API as well.
> fix: decode and validate all optionals.

- src/Data/Food/Ingredient.elm
- src/Data/Food/Query.elm
- src/Data/Textile/Query.elm
The food API wasn't properly handling the `byPlane` ingredient parameter in `POST`, see [Notion card](https://www.notion.so/Inconsistance-UI-API-sur-mango-non-ue-9da4a84239b741efafd8c6620622c466).
The patch fixes the issue.
There's a lot of tech debt in the way we parse the food query, but this would be HUGE work to properly refactor and should probably be assessed and prioritized better at a more appropriate time, so… this patch basically just patches and fixes the issue in the *least* dirty way.
The test suite still passes, which is good. To test the patch works, ask for the Non-EU Mango to the patched food API (I'm running it againt the local branch and server):
```
curl -sS -X POST "http://localhost:1234/api/food" \
-H "accept: application/json"\
-H "content-type: application/json"\ …
```
> fix(api): handle ingredient plane transport in food POST api.

- bin/download_github_releases.py
When deploying on scalingo we download all releases without checking if it's a draft one, it may cause problems if we want to use the draft functionality of releases to use `git-cliff` for example https://github.com/MTES-MCT/ecobalyse/pull/768.
Filter out releases that are draft.
The deploy to scalingo of this PR should download 11 releases and not more (we currently have 11 releases and some drafts).
> chore: don't download draft releases

- src/Views/Page.elm
When there is a PR deployed on Scalingo, a yellow banner is displayed at the bottom of the website to inform that we are on a staging env.
This banner hides the version number and/or the commit we're looking at.
Add a padding bottom to the footer when we are on a staging env.
The review app of this PR should not hide the version number when scrolling at the bottom of the page.
> fix: don't hide version information on staging

- public/data/textile/examples.json
Following the merge of https://github.com/MTES-MCT/ecobalyse/pull/757, `airTransportRatio` field is not needed anymore in exemples.
[Notion card](https://www.notion.so/Supprimer-la-valeur-fixe-airtransportratio-des-exemples-06d8fb81da934bb3a9c1f8783063e302)
Remove the field from the examples file.
Tests should still be green and scores should still be the same.
The test scenario described in this [Notion card](https://www.notion.so/Adapter-la-part-de-transport-en-avion-automatiquement-en-fonction-de-la-durabilit-76a7514bedb44d3298f401d69f09672f) should still work.
> chore: remove `airTransportRatio` from examples

- src/Data/Common/DecodeUtils.elm
- src/Data/Food/Query.elm
- src/Server.elm
- tests/Data/Food/QueryTest.elm
Nullable fields weren't nullable anymore when parsing JSON queries in the Food API. See [card](https://www.notion.so/Erreur-API-sur-exemple-de-la-Mangue-fd77338b263b44728b9b5df95bed0373).
This patch uses a more flexible utilitity from `Decode.Extra` to relax nullable value check. It also ensures always responding with errors encoded as JSON, for consistency.
Unit tests have been added so we're probably safe here, but toying around with the API manually might be a good idea.
```bash
$ curl 'https://ecobalyse.beta.gouv.fr/api/food' \
-H "accept: application/json" \
-H "content-type: application/json" \
-d '{"ingredients": [{"id": "milk","mass": 500,"country": "BR"}],"transform": null,"packaging": [],"distribution": "ambient","preparation":[]}'
Problem with the value at json.transform:
null …
```
> fix(api,food): nullable fields weren't nullable anymore.

- .github/workflows/node.js.yml
- .github/workflows/score_history.yml
Python builds in Github actions seem to [fail randomly on Github Actions](https://github.com/MTES-MCT/ecobalyse/actions/runs/11256209104/job/31297541397).
Try to use the now builtin [cache feature of the python github action](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages) to fix the problem.
The CI should be green on this PR.
> ci: use builtin python action cache for pipenv

- src/Data/Bookmark.elm
- src/Data/Object/Process.elm
- src/Data/Object/Query.elm
- src/Data/Object/Simulator.elm
- src/Page/Object.elm
- src/Views/Bookmark.elm
- src/Views/Comparator.elm
- tests/Data/Object/SimulatorTest.elm
The first version of the object interface doesn't manage bookmarks.
Implement the bookmark mechanism already available for the food and textile sections.
The `toString` on the `Query` object to find a default name for the bookmark may be questionnable.
Go on the review app https://ecobalyse-pr781.osc-fr1.scalingo.io/#/object/simulator and try to save/load simulations for the object interface using the bottom right tab.
> feat: add bookmarks for objects

- .github/workflows/create_release.yml
- bin/build-specific-app-version.sh
We have an error in production when logged-in and going from old version back to the `2.4.0` in the selector.
Add the encrypted file for objects when creating the version.
I’ve modified the already published version by adding the encrypted `processes_impacts_object.json.enc` manually and redeployed the production, so it should be working now. We don't need to land this patch ASAP, it can wait for the next release.
We will only be able to test it in the next release.
> fix: create object encrypted file for versions

- public/data/object/examples.json
- public/data/object/processes.json
- src/Data/Bookmark.elm
- src/Data/Object/Process.elm
- src/Data/Object/Query.elm
- src/Data/Object/Simulator.elm
- src/Page/Object.elm
- src/Views/Comparator.elm
- src/Views/ImpactTabs.elm
- tests/Data/Object/SimulatorTest.elm
- The simulator doesn't show masses (total and per-item)
- The "add item" button is missing when the product items list is empty.
- When selecting an existing example or bookmark, we'd like to fill its name in the new bookmark text input. 
- We'd also like a more meaningful query string representation than what we currently have.
- We want to render the steps impact distribution chart in the sidebar.
Implement aforementioned tasks.
- Check that the simulator renders total and per-item masses
- Check that we always have an "add item" button rendered.
- Check that an existing bookmark or example name is filled in the bookmark input text.
- Check that suggested bookmark names are more convenient than what we have now.
- Check that the step impacts distribution chart is rendered properly.
> fix: improve object simulator.

- .env.sample
- README.md
- index.js
- src/Data/Dataset.elm
- src/Data/Object/Process.elm
- src/Data/Session.elm
- src/Main.elm
- src/Page/Explore.elm
- src/Page/Explore/ObjectExamples.elm
- src/Page/Explore/ObjectProcesses.elm
- src/Page/Object.elm
- src/Views/Format.elm
- src/Views/Page.elm
There is currently no Object examples and processes explorer, as we have for textile and food.
Add explorer pages for browsing available examples and processes.
The patch introduces a new `ENABLE_OBJECT_SECTION` env var which allow configuring if the Object section should be rendered or not, the same way it's done for Food with `ENABLE_FOOD_SECTION`. When testing the patch locally, don't forget to set this var to `True` to show the menu entries.
Check that these two pages work as intended:
- [Object examples explorer](https://ecobalyse-pr803.osc-fr1.scalingo.io/#/explore/object/object-examples) and [a detailed example page](https://ecobalyse-pr803.osc-fr1.scalingo.io/#/explore/object/object-examples/7d78d30e-7c35-451f-b8ab-e590f39ed0e8)
- [Object processes …
> feat: add object explorer pages.

- tests/Data/Food/RecipeTest.elm
- tests/server.spec.js
We have differences in results between local computer and server-ci. Maybe because of processor architecture (arm64 vs x86).
As a results tests are failing either in local or on server-ci
As a temporary fix, allow more tolerance in tests floating points comparison. Going from 1e-16 toleranc to 1e-12 seems reasonable and fix my tests.
> chore: add tolerance to tests comparison

- src/Data/Textile/Simulator.elm
- src/Page/Api.elm
- src/Page/Food.elm
- src/Page/Object.elm
- src/Page/Textile.elm
- src/Views/Score.elm
- src/Views/Sidebar.elm
- tests/server.spec.js
Summing the scores of each step doesn't match the score displayed in the sidebar. Ineed, the main score displayed in the sidebar takes into account the durability (=totalImpacts score/durability) but the scores displayed for each step doesn't take into account the durability.
This is confusing.
[Notion card ](https://www.notion.so/Ajouter-le-score-hors-durabilit-ebd0fec910fa408491fec616923edca3)
Display, below the actual score, the score without the durability taken into account.
- Go on the textile tab
- Choose "T-shirt coton (150g) - Majorant par défaut"
- Check that 2 scores are displayed in the sidebar, "1 854 Pts" and "1 242 Pts hors durabilité"
- Check that 1242 is the sum of all the impacts scores of each step: 486+1.96+48.40+3.25+43.64+1.63+396+1.63+38.10+65.07+1.18+114+41.73=1242. …
> feat: display score without durability

- src/Data/Object/Process.elm
> fix: fix encoded display name field.

- public/pages/api-faq.md
- src/Page/Api.elm
[User Story](https://www.notion.so/Cr-er-une-FAQ-pour-l-API-751d592389df4adcaced8758409223d8)
Same questions come over and over on Mattermost, it's time to create a FAQ page for the API.
Create a FAQ page for the API.
I don't have the guts to elaborate on commercial and EI intellectual property aspects in this FAQ (eg. "can I use the API results for commercial projects?" and so on), feel free to jump in with legalese provided you'll assume adding, maintaining and take responsibility of it over time.
Check that the page is properly linked from the API page and answers most common questions one could ask about it. Also check for typos and phrasing.
> feat: add API FAQ page.

- data/common/import_.py
We cannot run two imports in parallel because the csv files are unzipped in the same directory.
Unzip in a temporary folder instead
Extract two clones of ecobalyse in two different folders, and launch the make process at the same time. Check both work.
> refactor: unzip in a temporary folder instead

- public/data/object/examples.json
- src/Data/Object/Query.elm
- src/Data/Object/Simulator.elm
- src/Page/Object.elm
- src/Views/Format.elm
- tests/Data/Object/SimulatorTest.elm
We want to be able to model the component notion. See [the card](https://www.notion.so/Objet_V0-S-lection-des-composants-79ca63b368524ee0b1f06321aa1878c5) for more details.
Add a level above the processes with a name and a quantity.
Currently, components are built on the file from the example file. Their uniqueness is based on their name, it should be improved later on with component ids and a file listing the possible components.
It's not possible to modify processes on purpose, it should come later on.
Tests need to be added.
- Go on the object tab
- Select the "Chaise", score should be 422
- Select the  "Table", score should be 3 979
- Add and remove some components: score should be updated accordingly
- Expand the "Procédés" summary and check that the totals impacts and mass of the …
> feat: add components to objects

- src/Data/Textile/Economics.elm
- tests/Data/Textile/EconomicsTest.elm
[Notion card](https://www.notion.so/Largeur-de-gamme-modification-des-seuils-135b056852fc809b9595ccfd6939ff97)
Two problems:
1. We want the thresholds applied to clearly distinguish:
- Ultra fast fashion which should be at 0%
- Fast fashion which should be around 50%
2. We do not want the thresholds to:
- Penalize brands that offer, for example, clothing for large sizes (this does not increase the choice offered to people who are not concerned)
Update thresholds; today the “largeur de gamme” index takes the following thresholds:
- 100% when the number of references is less than 3000
- 80% for 6,000 references
- 50% for 10,000 references
- 0% when the number of references is greater than 50,000
These should be replaced as following:
- 100% when the number of references is less than 1,000
- …
> feat(textile): update number of references index thresholds.

- bin/build-db
- public/data/object/components.json
- public/data/object/examples.json
- src/Data/Bookmark.elm
- src/Data/Dataset.elm
- src/Data/Object/Component.elm
- src/Data/Object/Db.elm
- src/Data/Object/Process.elm
- src/Data/Object/Query.elm
- src/Data/Object/Simulator.elm
- src/Page/Explore.elm
- src/Page/Explore/ObjectComponents.elm
- src/Page/Explore/Table.elm
- src/Page/Object.elm
- src/Static/Json.elm-template
- src/Views/Format.elm
[Notion card](https://www.notion.so/Migrer-les-donn-es-de-composants-Objets-dans-un-fichier-JSON-d-di-et-proposer-une-premi-re-version--d91e4f0aeebb41a8b2ad618389de02b3)
We don't have a components database and explorer for objects and veli just yet. Also, a component db and handling api would establish good foundations for further work with textile trims (though this patch doesn't make components totally generic just yet, but that'd be the next step).
Introduce a components JSON database with reusable default components for objects and veli. Add a component explorer as well.
Ensure the explorer works well and that the objects and veli simulators still work as expected.
> feat: introduce components db

- data/common/import_.py
the Agribalyse source file is patched with sed at import, but CTCPA is also patched and shoud not.
Check we target "AGB3..." and not all files containing "AGB"
`make clean import` and check you don't have `sed` errors like that:
`sed: can't read /tmp/tmpepq615gb/Export: No such file or directory`
> refactor: patch only AGB, not CTCPA which also contains 'AGB' in the filename

- package.json
Our e2e test suite sometimes fails because of a 50ms timeout exhausted.
50ms is not much, increase that value to 100ms.
Test suite should be green.
> chore: increase API test timeout

- public/data/food/processes.json
- src/Data/Food/Process.elm
- src/Page/Explore/FoodProcesses.elm
The `system_description` field in the food processes file format is obsolete and redundant with the `source` one ([Mattermost discussion](https://mattermost.incubateur.net/fabnum-mte/pl/crb13ou4s7rx9nhztaa8kgfwww))
Remove it.
This one is straightforward, the build should be green.
ecobalyse-private: chore/remove-unused-system-description
> chore(data): remove system_description process field.

- server.js
Users are reporting errors when using the versioned API.
We are serving hardcoded versions of the detailed files instead of the one shipped with the release.
Serve the correct files encoded with the release instead of files that don't exist on the disk.
`curl https://ecobalyse-pr851.osc-fr1.scalingo.io/versions/v2.7.0/api/textile/countries` should return the country list:
```json
[
{
"code": "---",
"name": "Pays inconnu (par défaut)"
},
{
"code": "REO",
"name": "Région - Europe de l'Ouest"
},
{
"code": "REE",
"name": "Région - Europe de l'Est"
},
{
"code": "RAS",
"name": "Région - Asie"
},
{
"code": "RAF",
"name": "Région - Afrique"
},
{
"code": "RME",
"name": "Région - Moyen-Orient"
},
{
"code": "RLA",
"name": "Région - Amérique Latine"
},
{
"code": "RNA",
"name": "Région - Amérique du …
```
> fix: api error on old versions

- .github/workflows/score_history.yml
Build is failing on `master` for the `score_history` workflow because it was not updated for `transcrypt`.
Add the `TRANSCRYPT_KEY` env variable and install `transcrypt` in the workflow.
Run the workflow by hand here https://github.com/MTES-MCT/ecobalyse/actions/workflows/score_history.yml and check that everything works as expected.
> ci: fix score_history workflow for transcrypt

- bin/run-transcrypt.sh
When `transcrypt` is already configured for your repo locally and you run `npm install` you get an error saying that the current repository is already configured because the npm `postinstall` step is executed no matter what.
Check if the repo was already configured with `transcrypt` before trying to configure it.
`npm ci` should not report any error and should display this message:
ℹ️ `transcrypt` was already configured for this repo, skipping.
The ci should be green, validating the case that everything still works fine when setting up a new repo from scratch.
> fix(dev): npm ci error with `transcrypt`

- src/Data/Component.elm
- src/Data/Dataset.elm
- src/Data/Object/Db.elm
- src/Data/Object/Query.elm
- src/Data/Object/Simulator.elm
- src/Page/Explore.elm
- src/Page/Explore/ObjectComponents.elm
- src/Page/Object.elm
- src/Views/Comparator.elm
- src/Views/Format.elm
- src/Views/ImpactTabs.elm
- tests/Data/ComponentTest.elm
- tests/Data/Object/SimulatorTest.elm
- tests/TestUtils.elm
[User story](https://www.notion.so/Abstraire-les-composants-dans-le-code-ecb8ebdfccff4175a2994e0613792466)
Today we have object-specific components, but we need them to be domain-agnostic so we can use the same code and data source format to handle food, object and textile ones.
Move component impacts computation into `Data.Component` module including `Result` to make the calculation domain-agnostic.
As always with code refactoring, ensure the exposed/updated api makes sense and is as much future-proof as possible.
Ensure that nothing breaks:
- tests should be green, including added ones
- Object components explorer should work as previously
- Object and véli simulators should work as previously
> refactor: abstract components.

- public/data/textile/components.json
- public/data/textile/examples.json
- src/Page/Explore.elm
- src/Page/Explore/TextileExamples.elm
More example garments should feature trims ([Notion card](https://www.notion.so/Sc-nario-par-d-faut-pour-les-trims-1d3abd5235cc46b4bf746d090f094fdd)). We should also render them in the textile examples explorer.
Update textile examples with new trims data. Render them in the textile examples exporer.
Check that the updated textile examples (see notion card) feature the expected trims. Check the textile examples explorer.
> feat(data,ui): add trims to more textile examples, render them in explorer

- src/Page/Textile.elm
Users want trim impact and amount details, as we have in the Object simulator.
Allow expanding textile trim details as we allow it for object components.
Check that trim details are expanded and collapsed when clicking the black arrow next to a trim row.
> feat: allow expanding trim details.

- src/Data/Session.elm
- src/Main.elm
- src/Views/Alert.elm
- src/Views/Page.elm
Context: comment from @vjousse (https://github.com/MTES-MCT/ecobalyse/pull/878#issuecomment-2577039188):
> the problem is with the local storage decoding. The `staff` field is missing in my local storage (so I suppose that the Elm json decode is failing), if I add it by hand it works again as expected.
No error message is rendered to users when decoding their serialized session data fails.
Warn the user that decoding the session has failed, with useful information on how to report the problem:
Tamper with serialized user session data in localstorage and check that an error message is rendered to the user.
> fix: Warn on session data decoding error.

- Pipfile
- Pipfile.lock
> An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. The strip_tags() method and striptags template filter are subject to a potential denial-of-service attack via certain inputs containing large sequences of nested incomplete HTML entities.
https://github.com/MTES-MCT/ecobalyse/security/dependabot/53
> chore(security): upgrade django to >=5.1.4.

- .github/workflows/create_release.yml
The current release workflow fails because it’s missing the transcrypt key env variable. See https://github.com/MTES-MCT/ecobalyse/actions/runs/12748629218
Add the env variable and allow the possibility to run the workflow by hand with a dispatch in case of failure.
Hard to test as it is only testable when creating a release…
Once it has been approved, I’ll remove the already created tag and restart the release process by hand using the workflow dispatch added here.
> fix: allow workflow dispatch for release creation

- src/Page/Explore/Processes.elm
Process explorers don't currently show waste, density, elec and heat fields.
Show them.
Check that these fields are added as columns in process explorer tables and as rows in process explorer details modals.
> feat: show heat, elec, waste, density in process explorer.

- src/Page/Home.elm
See [Notion card](https://www.notion.so/Supprimer-le-dernier-lien-vers-le-calculateur-alimentaire-depuis-la-page-d-accueil-7cd1bcc109f8421aa1949afb553ea407?d=9058e9edaa1f4869a7cc79a2461397e8)
> fix: hide link to food from the homepage.

- src/Views/Component.elm
Sometimes a good laugh's worth a thousand words 😄
> fix: restrict selectable components to scoped ones.

- public/data/object/components.json
- src/Data/Component.elm
- src/Page/Explore/Components.elm
- src/Views/Component.elm
- tests/Data/ComponentTest.elm
[Notion card](https://www.notion.so/Composants-de-n-proc-d-s-mati-res-et-n-proc-d-s-transformation-b30599ba654c46758f962eabe6b8595c)
We need to render the details of applied transform processes to each component element material.
Render them.
A bug was fixed where energy was applied as kWh instead of MJ for heat consumption in transform process impacts computation (https://github.com/MTES-MCT/ecobalyse/pull/907/commits/8ce0548ffebdbc29f83c0787c80b32e8ae89cc34).
Check that the UI conforms to users expectations (see card)
> feat: render component transforms

- public/data/textile/products.json
- src/Data/Textile/Product.elm
- src/Data/Textile/Query.elm
- src/Page/Textile.elm
See [Notion card](https://www.notion.so/Les-cat-gories-en-textile-doivent-avoir-les-trims-par-d-fauts-eb163196faa841da941283c831e1c42f) which exhaustively describes the use case and expectations.
> feat(textile,ui): apply default trims on product category change

- src/Data/Textile/Simulator.elm
- src/Page/Textile.elm
- tests/Data/Textile/SimulatorTest.elm
[Notion card](https://www.notion.so/Impacts-accessoires-non-inclus-dans-le-score-hors-durabilit-7b4e7f70c11f4d51a4c25635d235dfd8)
> fix: include trims impacts to score without durability.

- src/Page/Explore/FoodIngredients.elm
- src/Page/Explore/Processes.elm
source Identifier has no sense outside of a SimaPro instance. The agb 3.1.1  AGRIBALU identifiers will be lost when moving to agb 3.2.
See :
https://www.notion.so/Agribalyse-3-2-library-dans-SimaPro-1a4b056852fc80909005dcca6b97979a
https://www.notion.so/Identifiants-de-proc-d-s-1a5b056852fc80c19eb8debdb1ece392
Remove these identifiers from the explorer.
Check that there are no MTE or AGRIBALU in the explorer
> fix: remove the sourceId from the explorer

- scalingo.json
Currently food, objects and veli are disabled by default in review apps. This make reviewing changes in these vertical more difficult.
Use `scalingo.json` to set 
`
"ENABLE_FOOD_SECTION": {
"value": "True"
},
"ENABLE_OBJECTS_SECTION": {
"value": "True"
},
"ENABLE_VELI_SECTION": {
"value": "True"
},
`
So that review apps display all verticals, but it doesn't affect production
Check that the review app has a food, objects and veli tab
> chore: enable all verticals in review apps

- openapi.yaml
- src/Page/Api.elm
Query-string based API endpoints have been complicated to maintain over time and don't provide much value over their much simpler POST+JSON equivalent. We should deprecate these redundant GET endpoints.
Note: We'll remove them completely in the following major version to clear redundancy and clean a bunch of tech debt along the way (work has been started in #951).
Deprecate these API endpoints which already have a POST+JSON equivalent:
- `GET /food`
- `GET /textile/simulator`
- `GET /textile/simulator/{impact}`
- `GET /textile/simulator/detailed`
These will be removed in 5.0.0.
Endpoints should keep working, only the documentation should denote them as deprecated:
> chore: deprecate textile simulator API GET endpoints.

- package-lock.json
- package.json
We get a daily application crash with the following log:
```
2025-03-06 01:20:27.700694367 +0000 UTC [web-1] <--- JS stacktrace --->
2025-03-06 01:20:27.700703803 +0000 UTC [web-1] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
2025-03-06 01:20:27.700706909 +0000 UTC [web-1] ----- Native stack trace -----
2025-03-06 01:20:27.701695609 +0000 UTC [web-1] 1: 0xb86ecf node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
2025-03-06 01:20:27.702335043 +0000 UTC [web-1] 2: 0xef74d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
2025-03-06 01:20:27.702951980 +0000 UTC [web-1] 3: 0xef77b7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails …
```
> fix: memory leak in node 20.16 and 20.17

- Pipfile
- Pipfile.lock
> An issue was discovered in Django 5.1 before 5.1.7, 5.0 before 5.0.13, and 4.2 before 4.2.20. The django.utils.text.wrap() method and wordwrap template filter are subject to a potential denial-of-service attack when used with very long strings.
https://github.com/MTES-MCT/ecobalyse/security/dependabot/59
> fix(security): upgrade django to 5.1.7.

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/task.md
We want to explore switching to Github Project.
Introduce an issue template to use Github project for managing the project backlog.
Once merged, creating a new issue should use this new template
> chore: add issue template

- openapi.yaml
- package-lock.json
- package.json
- server.js
- tests/server.spec.js
This patch fixes 4 problems with the API:
- The `openapi.yml` schema didn't declare required schema fields properly ([source](https://chat.ecobalyse.fr/ecobalyse/pl/twdih8ewwtd6bnqarskzpmkq3h))
- The required fields now appears on top of the fields list for convenience
- Several product categories were missing from the schema enum
- Invalid JSON body passed to POST endpoints generated a `text/html` response, possibly breaking clients
> fix(api): improve API docs and JSON data validation

- index.js
should fix #1051
@vjousse dunno how to check that it actually fixes version switching WPOD, and how to patch generated versions :/
> fix: default to empty string on BACKEND_API_URL not set

- bin/check-ecobalyse-data-sync.sh
Github action `ecobalyse-data sync`is not up to date with the merging of processes.json in a single file
Update Github action `ecobalyse-data sync` so that it check the sync of the single file `processes.json`
> chore: update ecobalyse data sync

- src/Page/Auth.elm
From @camcoq-start ([source](https://github.com/MTES-MCT/ecobalyse/issues/1052#issuecomment-2969555702))
There's no visual feedback when a token has been copied to the user's clipboard.
Add a success notification.
> feat: add success notification on api token copied.

- lib/instrument.js
reduce sentry tracesSampleRate (800k events/day)
> Sentry client generates too much data on our shared instance
> reduce tracesSampleRate
> https://docs.sentry.io/platforms/javascript/configuration/sampling/
> chore: reduce sentry tracesSampleRate

- e2e/lib.js
- playwright.config.js
Immediately close a notification as soon as a test assertion has been made about it, to avoid intermittent e2e test failures.
> fix: improve e2e tests reliability wrt notifications

- backend/.env.sample
- backend/.env.testing
- backend/README.md
- backend/src/app/cli/commands.py
- backend/src/app/config/app.py
- backend/src/app/domain/journal_entries/deps.py
- bin/load-fixtures.sh
- bin/reset-docker-db.sh
- tests/backend/data_fixtures.py
- tests/backend/integration/conftest.py
- tests/backend/integration/test_access.py
- tests/backend/integration/test_journal_entries.py
When displaying the history of a component, the backend throws an error 500 when one of the users in the history is not the current user. Moreover the format of the default 500 exception doesn’t follow the problem details spec (`status_code` instead of `status`) https://datatracker.ietf.org/doc/html/rfc9457
Retrieve the related user when fetching journal entries and fix the default exception format.
The two useless `.env` files of the `backend/` directory have been removed too.
Was fixed with TDD, so tests have been added to check that it works as expected.
If you want to test by hand: create 2 different users, and modify the same component with the two different users. You shouldn’t see any error.
> fix: 500 error on journal history

- backend/src/app/domain/accounts/controllers/access.py
- backend/src/app/domain/components/controllers/component.py
- src/Request/BackendHttp.elm
- tests/backend/integration/test_access.py
- tests/backend/integration/test_components.py
The Elm backend http client doesn't handle an empty http response by (eg. for 204 responses), let's fix that.
Default empty body string to `"null"` so it's always valid JSON.
Backend API now responds with 204 for deletions.
Tests have been updated, so… not much. Maybe manually ensure that deleting a component from the admin doesn't explode your computer.
> refactor: handle empty responses from the backend api

- bin/update-version.sh
Deploy error on Scalingo `./bin/update-version.sh: line 14: python: command not found`
Add missing `uv run`
New deploy on production…
> fix: add missing `uv run`

- .proxyrc.json
- backend/src/app/cli/commands.py
- bin/build-specific-app-version.sh
- bin/patch_files_for_versions_compat.py
- index.js
- packages/python/ecobalyse/ecobalyse/0002-patch-index-js-client-path-backend.patch
- packages/python/ecobalyse/ecobalyse/patch_files.py
- pyproject.toml
- servers.conf.erb
- When browsing the `v6.0.0` version in the selector, a `/` is added to the `clientUrl` causing http errors because of `//` in urls
- Versions under the `/versions/v6.0.0/` url for example are doing HTTP calls to `/versions/v6.0.0/backend` instead of `/backend`
- Use a regex to remove all trailing `/` in clientUrl
- Patch the v6.0.0
- Use a nginx rewrite rule for backend calls
I was unable to find how to manage the `.proxyrc.json` of Parcel to handle URLs rewriting in a clean way, so I’ve hardcoded the version number for now. Happy to receive some help here.
The best solution for me would be to use nginx locally like in production to avoid those kind of problems and possible errors.
The `v6.0.0` release have been patched and deployed in production.
In the review app, browse to the …
> fix: backend url rewriting

- server.js
Serving processes for versions fails with a JSON decoding error because we are returning real JSON for processes instead of a string containing the JSON.
Commit here: https://github.com/MTES-MCT/ecobalyse/commit/9c3806a3374c6ea7c9dc577d4fe14c4274a6af2f#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406fR248-R253
Always return a string for processes of old versions.
Another solution would be to just remove this version mess 🙄
Login to the unreleased version, display detailed impacts, switch to v6.1.1 in the selector and go back to the unreleased, you should see no error.
> fix: JSON parsing in versions

- lib/http.js
- tests/lib/http.spec.js
Posthog connects to the `eu-assets.i.posthog.com` external host so we must add to our Content Security Policy configuration in order to collect events.
> fix: update CSP for posthog requirements

- .env.sample
- README.md
- index.js
- src/Data/Session.elm
- src/Main.elm
- src/Request/Version.elm
Allow specifying `VERSION_POLL_SECONDS` to tweak the current version polling interval
> feat: allow configuring version polling interval

- backend/src/app/domain/accounts/services.py
- backend/src/app/domain/accounts/tasks.py
- src/Page/Auth.elm
- src/Views/Page.elm
- tests/backend/integration/test_access.py
fixes #1268 
It looks like people are clicking on the login link twice and get a 403 error as the token can only be used once.
Improve already used token error message, give visual feedback to the users when they are clicking on the send email links (to avoid clicking twice if the backend doesn’t respond fast enough), improve login email content by specifying that the link can only be used once.
Test the login/signup process.
Clicking on « Recevoir un email de connexion » should disable the button and briefly display « Email de connexion en cours d’envoi… » before redirecting.
Clicking on « Valider mon inscription » should disable the button and briefly display « Envoi de la demande d’inscription en cours… » before redirecting.
Click on the link received by email, see that everything …
> chore: improve token handling feedback

- .env.sample
- .gitignore
- bin/scalingo_api.py
- packages/python/ecobalyse/ecobalyse/scalingo.py
It’s hard to get information about logs on scalingo as they are archived in a non friendly interface.
Create a script that can download the logs and try to parse some information out of it.
I’m using python mutliprocessing to speed up the log parsing as it takes quite some time without it.
```python
uv run bin/scalingo_api.py log-archives
```
Should display the slowest log lines, and logs should have been downloaded in `./archives_logs` directory.
> feat: list and parse scalingo logs

- openapi.yaml
Carton and Cuisson have changed UUID and are used as examples in the food API. 
We currently get there results on 7.1.0 and staging:
```json
{
"error": {
"packaging": "Procédé introuvable par id : 25595091-35b6-5c62-869f-a29c318c367e",
"transform": "Procédé introuvable par id : 83b897cf-9ed2-5604-83b4-67fab8606d35"
},
"documentation": "https://ecobalyse.beta.gouv.fr/#/api"
}
```
just fixed the uuids
Try the food API examples and check there are no errors
> fix: fixed food API examples (food "Carton" and "Cuisson")

- src/Page/Home.elm
- src/Views/Page.elm
- styles.scss
refs #1368
This patch updates the CTA to link to the textile simulator in version 7.0.0, which is the official regulatory one. It doesn't update the link in the header navigation menu, but I can do that too if required. I've added a banner on the production textile page (today in 7.1.1, tomorrow most likely in 7.2) to indicate that the regulatory version is 7.0.0 with a link to it. Banner text is mine, but could probably be improved.
I feel it's kinda ok and not too confusing, though I'm all ears for improvements.
> feat(ui): update textile CTA links to regulatory version, add banner

- server.js
- src/Data/Textile/Simulator.elm
- src/Server.elm
- src/Server/Request.elm
- tests/Server/RouteTest.elm
- tests/Server/ServerTest.elm
- tests/TestUtils.elm
The `webUrl` returned by the API is hardcoded to `ecobalyse.beta.gouv.fr`, even when running on the staging or a review app:
```
{
"webUrl": "https://ecobalyse.beta.gouv.fr/........
```
Also, when using a versioned API, it doesn't contain the version, making the resulting scores in the web version possibly differing from the ones in the API response. Note: this patch takes over #1363 in this regard and fixes #1360
Instead of a harcoded FQDN, use the host transmitted from the request. Also reflect the version used for the API in the Web urls.
Check in the API, when running a request, that you get the right FQDN:
Example on this PR:
```
{
"webUrl": "https://ecobalyse-staging-pr1381.osc-fr1.scalingo.io#/food/ecs/ey.....
```
With versioned APIs, check that the version is preserved in the web …
> fix(api): expose server fqdn and version to urls in responses

- bin/download_github_releases.py
fixes https://github.com/MTES-MCT/ecobalyse/issues/1038
Don’t deploy `prerelease` versions.
Currently you can access https://ecobalyse.beta.gouv.fr/versions/v6.0.0/ even if it’s not in the version selector as versions that are marked as `prerelease` are still deployed.
https://ecobalyse-staging-pr1394.osc-fr1.scalingo.io/versions/v6.0.0/ should not be available anymore on this scalingo deploy, it should redirect to https://ecobalyse-staging-pr1394.osc-fr1.scalingo.io/
> chore: don’t deploy prereleases

- e2e/auth.spec.js
- e2e/lib.js
- src/Page/Auth.elm
A lot of users report that when clicking their magic links, an error says the link is already expired. This must be because their email client fetches the content behind the link, therefore expiring the one-time token.
[Discussion happens here](https://mattermost.incubateur.net/fabnum-mte/pl/syc3ao89spbpumk9odyb1p3khy)
This patch implements a new login confirmation screen with a mandatory click, requiring a manual action email client can't and won't do.
Login on the review app: a button should ask confirmation for effective login.
Note: I've asked this specific user to test this review app so we can see if the patch solves the problem for them.
Edit: it fixes the issue:
> Bonjour Nicolas, 
>
>Merci pour votre réponse, j'ai essayé avec le compte stagging et effectivement cela fonctionne ! …
> fix(auth): require manual login confirmation
